ChildMindInstitute/mindlogger-backend-refactor

src/apps/applets/crud/applets.py, src/apps/applets/crud/roles.py, src/apps/authentication/api/auth.py, src/apps/users/api/users.py, src/apps/users/crud.py, src/apps/users/domain.py, src/apps/users/errors.py, src/apps/users/router.py, src/infrastructure/database/crud.py, src/middlewares/errors.py
Includes more consistent business logic for CRUD operations
=> Update user/auth/applets CRUD operations

src/apps/authentication/api/auth.py, src/apps/users/domain.py
=> M2-372: Login/Logout api

src/apps/authentication/router.py, src/apps/invitations/router.py, src/apps/shared/domain/response.py, src/apps/shared/errors.py, src/apps/users/router.py, src/main.py
This is fixed only for high priority parts of an application
=> Resolved m2-391: Fixed missed swagger response schema

README.md, docker-compose.yaml, pyproject.toml, src/apps/activities/db/schemas/__init__.py, src/apps/shared/domain/response/errors.py, src/apps/shared/errors.py, src/apps/shared/test/client.py, src/apps/users/crud.py, src/apps/users/errors.py, src/apps/users/tests/test_password.py, src/apps/users/tests/test_user.py
* Env variables are fixed
* Docker compose is updated according to new environment variables
* pyproject.toml file tests section is updated according to the new environment variables
* Password update test is fixed
* User's test is fixed according to the new HTTP status code
=> Code quality is improved

src/apps/schedule/api/schedule.py, src/apps/schedule/crud/events.py, src/apps/schedule/crud/periodicity.py, src/apps/schedule/router.py, src/apps/schedule/service/schedule.py, src/apps/schedule/tests/test_schedule.py
Task: https://mindlogger.atlassian.net/browse/M2-380
=> Delete API for schedule 

src/apps/schedule/api/schedule.py, src/apps/schedule/crud/events.py, src/apps/schedule/crud/periodicity.py, src/apps/schedule/db/schemas.py, src/apps/schedule/domain/schedule/internal.py, src/apps/schedule/router.py, src/apps/schedule/service/schedule.py, src/apps/schedule/tests/test_schedule.py, src/infrastructure/database/migrations/versions/2023_01_26_14_35-schedule_event_periodicy_etc.py
- Update API 
- Minor changes in schema
https://mindlogger.atlassian.net/browse/M2-495
=> M2-495: Update API for scheduled events

src/apps/schedule/api/schedule.py, src/apps/schedule/crud/events.py, src/apps/schedule/crud/periodicity.py, src/apps/schedule/db/schemas.py, src/apps/schedule/domain/schedule/internal.py, src/apps/schedule/domain/schedule/public.py, src/apps/schedule/router.py, src/apps/schedule/service/schedule.py, src/apps/schedule/tests/test_schedule.py, src/infrastructure/database/migrations/versions/2023_01_26_14_35-schedule_event_periodicy_etc.py
Task : https://mindlogger.atlassian.net/browse/M2-377
Event count per activity and flow API for schedule app.
=>  event count per activity and flow API

src/apps/applets/service/applet/create.py, src/apps/applets/service/applet/update.py, src/apps/applets/tests/test_applet.py, src/apps/schedule/api/schedule.py, src/apps/schedule/crud/events.py, src/apps/schedule/crud/periodicity.py, src/apps/schedule/db/schemas.py, src/apps/schedule/domain/constants.py, src/apps/schedule/domain/schedule/base.py, src/apps/schedule/domain/schedule/public.py, src/apps/schedule/domain/schedule/requests.py, src/apps/schedule/fixtures/activity_events.json, src/apps/schedule/fixtures/events.json, src/apps/schedule/fixtures/flow_events.json, src/apps/schedule/fixtures/periodicity.json, src/apps/schedule/router.py, src/apps/schedule/service/schedule.py, src/apps/schedule/tests/test_schedule.py, src/infrastructure/database/migrations/versions/2023_01_26_14_35-schedule_event_periodicy_etc.py
- delete all by user
- create default logic
- fixtures
- fix swagger schemas for events(camelcase issue)
- create default event on activity or flow create
=> #M2-527 Event Always Available logic

src/apps/schedule/domain/schedule/requests.py
https://mindlogger.atlassian.net/browse/M2-977
=> m2-977:description added

src/apps/activities/domain/reusable_item_choices.py, src/apps/activities/tests/test_reusable_items.py, src/infrastructure/database/migrations/versions/2023_03_22_11_32-add_alerts.py
https://mindlogger.atlassian.net/browse/M2-959
=> m2-959: fix tokenValue validation

src/apps/schedule/api/schedule.py, src/apps/schedule/crud/events.py, src/apps/schedule/domain/constants.py, src/apps/schedule/domain/schedule/__init__.py, src/apps/schedule/domain/schedule/filters.py, src/apps/schedule/service/schedule.py, src/apps/schedule/tests/test_schedule.py
https://mindlogger.atlassian.net/browse/M2-1730
https://mindlogger.atlassian.net/browse/M2-1562
=> m2-1730: filter respondent_id events all

src/apps/library/api.py, src/apps/library/domain.py, src/apps/library/router.py, src/apps/library/service.py, src/apps/library/tests.py, src/apps/shared/paging.py
https://mindlogger.atlassian.net/browse/M2-2731
@Damirkhon @Tom1204 Please take a look to api result format it has been changed, it is ok ?
=> M2-2731 [Backend] Library: add pagination and search into cart

src/apps/applets/crud/applets.py, src/apps/workspaces/domain/workspace.py, src/apps/workspaces/service/workspace.py, src/apps/workspaces/test_workspaces.py
https://mindlogger.atlassian.net/browse/M2-2564
=> M2-2564: Add additional properties to the /workspaces/{workspace_id}/applets

src/apps/answers/tests/test_answer_for_cases.py, src/apps/library/domain.py, src/apps/library/service.py, src/apps/library/tests.py
https://mindlogger.atlassian.net/browse/M2-2620
=> [API] Applet Library: some properties have different names in "PublicLibraryItem" data model. Wrong 'subscaleSetting' property name.

src/apps/activities/fixtures/activity_item_histories.json, src/apps/answers/tests/test_answer_for_cases.py, src/apps/library/service.py, src/apps/library/tests.py
https://mindlogger.atlassian.net/browse/M2-2623
=> Fix empty slider response items

src/apps/answers/tests/test_answer_for_cases.py, src/apps/applets/fixtures/applet_histories.json, src/apps/library/crud.py, src/apps/library/tests.py
https://mindlogger.atlassian.net/browse/M2-2622
https://mindlogger.atlassian.net/browse/M2-2580
=> M2-2622, M2-2580: Provide "about", "image", "watermark"  to PublicLibraryItem

src/apps/library/domain.py
https://mindlogger.atlassian.net/browse/M2-2853
=> Add case for str in to-camelcase func in LibruaryItem

src/apps/answers/service.py, src/apps/answers/tests/test_answers.py
https://mindlogger.atlassian.net/browse/M2-2542
=> Identifier filter in summary

src/apps/applets/crud/applets.py, src/apps/applets/filters.py, src/apps/shared/paging.py, src/apps/shared/query_params.py, src/apps/workspaces/api.py, src/apps/workspaces/service/workspace.py, src/apps/workspaces/test_workspaces.py, src/config/service.py
https://mindlogger.atlassian.net/browse/M2-2580
=> Flat applets list

src/apps/alerts/domain.py, src/apps/alerts/ws_api.py
https://mindlogger.atlassian.net/browse/M2-2856
=> Add fields to ws handler and change result to camelCase

src/apps/alerts/api.py, src/apps/alerts/crud/alert.py, src/apps/alerts/domain.py, src/apps/alerts/service.py
https://mindlogger.atlassian.net/browse/M2-2882
=> Unread count on GET /alerts 

src/apps/alerts/crud/alert.py, src/apps/alerts/domain.py, src/apps/alerts/service.py, src/apps/alerts/test_alerts.py, src/apps/alerts/ws_api.py
add fields to Alerts GET:
- encryption
- workspace name 
- applet image url
- respondent id
=> Add additional fields to alert list

src/apps/alerts/domain.py, src/apps/library/domain.py, src/apps/shared/domain/base.py
https://mindlogger.atlassian.net/browse/M2-2893
=> encryption value of alert change to camelCase

src/apps/answers/crud/answer_items.py, src/apps/answers/filters.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py
https://mindlogger.atlassian.net/browse/M2-2542
=> Add flag to return all answers with null identifiers

src/apps/answers/crud/answer_items.py, src/apps/answers/filters.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py
https://mindlogger.atlassian.net/browse/M2-2542
=> M2 2542 Change filters logic for version and identifiers

src/apps/answers/crud/answers.py
https://mindlogger.atlassian.net/browse/M2-2641
=> M2-2641 Fix assessment data export

src/apps/library/api.py
https://mindlogger.atlassian.net/browse/M2-2620
=> m2-2620 Add camel case transformation on GET library/{pk}

docker-compose.yaml, src/config/rabbitmq.py, src/consumer.py
[M2-2827](https://mindlogger.atlassian.net/browse/M2-2827)
=> M2-2827 Fix rabbitmq message acknowledgment

src/apps/activities/domain/activity_item_base.py, src/apps/applets/tests/test_applet_activity_items.py
https://mindlogger.atlassian.net/browse/M2-2931
=> M2-2931 Allow condition logic for TimeRange item

src/apps/activities/services/activity.py
https://mindlogger.atlassian.net/browse/M2-1535
=> M2-1535: Added is_hidden to PreparedActivityItemUpdate

src/apps/applets/tests/test_applet_folder.py, src/apps/folders/crud.py, src/apps/folders/fixtures/folders.json, src/apps/folders/fixtures/folders_applet.json, src/apps/folders/service.py, src/apps/folders/test_folder.py
https://mindlogger.atlassian.net/browse/M2-2044
=> M2-2044: Fixed pinning/unpinning of applets in folders of shared workspace 

src/apps/answers/crud/answer_items.py, src/apps/answers/domain/answers.py, src/apps/answers/tests/test_answers.py
https://mindlogger.atlassian.net/browse/M2-2969
=> m2-2969: Remove isEdited field

src/apps/workspaces/crud/applet_access.py, src/apps/workspaces/crud/user_applet_access.py, src/apps/workspaces/domain/workspace.py, src/apps/workspaces/test_workspaces.py
https://mindlogger.atlassian.net/browse/M2-3072
=> M2-3072 Add reviewer respondents list to workspace/managers applet data

src/apps/applets/crud/applets_history.py, src/apps/applets/db/schemas/applet.py, src/apps/applets/service/applet.py
https://mindlogger.atlassian.net/browse/M2-2950
=> M2-2950 Update history on applet report changes

src/apps/applets/service/applet.py
https://mindlogger.atlassian.net/browse/M2-2840
=> m2-2840: Copy subscales and reports

src/apps/answers/service.py, src/apps/answers/tests/test_answers.py, src/apps/applets/fixtures/applet_user_accesses.json, src/apps/users/fixtures/users.json, src/apps/workspaces/crud/applet_access.py
[[Backend] Reviewer is able to see the non-assigned Respondent's Summary Tab on Dataviz](https://mindlogger.atlassian.net/browse/M2-2750)
=> M2-2750: Add check respondents for reviewer role

src/apps/answers/crud/answers.py
https://mindlogger.atlassian.net/browse/M2-3115
=> M2-3115 Add scheduled_event_id for completed entities grouping

src/apps/workspaces/service/user_access.py, src/apps/workspaces/test_workspaces.py, src/config/__init__.py
https://mindlogger.atlassian.net/browse/M2-2983
=> M2-2983 Allow manager remove not invited managers

src/apps/mailing/static/templates/applet_create_failed_en.html, src/apps/mailing/static/templates/applet_create_success_en.html, src/apps/mailing/static/templates/applet_edit_success_en.html, src/apps/mailing/static/templates/blocks/write_us_en.html, src/apps/mailing/static/templates/reset_password_en.html, src/apps/mailing/static/templates/response_alert_en.html, src/apps/mailing/static/templates/transfer_ownership_registered_user_en.html, src/apps/mailing/static/templates/transfer_ownership_unregistered_user_en.html
[M2-623](https://mindlogger.atlassian.net/browse/M2-623)
=> M2-623 Fix "write-us" email link

src/apps/activities/services/activity_item.py
https://mindlogger.atlassian.net/browse/M2-1535
=> M2-1535 Override is_hidden to avoid using default logic

src/apps/answers/crud/answers.py
https://mindlogger.atlassian.net/browse/M2-3100
=> M2-3100 Change answer soft delete to hard delete

src/apps/workspaces/crud/user_applet_access.py
https://mindlogger.atlassian.net/browse/M2-3114
=> M2-3114 Fix workspace respondents reviewer access

src/apps/answers/domain/answers.py
https://mindlogger.atlassian.net/browse/M2-2625
=> M2-2625 Convert scheduled_datetime to ms in data export

src/apps/applets/crud/applets.py
https://mindlogger.atlassian.net/browse/M2-3098
=> M2-3098: Filter by soft_exists in applet list for web app

src/apps/activities/domain/scores_reports.py, src/apps/authentication/crud.py, src/apps/jsonld_converter/service/document/activity.py, src/apps/jsonld_converter/service/document/conditional_logic.py, src/apps/jsonld_converter/service/document/subscale.py
https://mindlogger.atlassian.net/browse/M2-2963
=> M2 2963 scores reports

src/apps/activities/fixtures/activity_histories.json, src/apps/answers/domain/answers.py, src/apps/answers/fixtures/arbitrary_server_answers.json, src/apps/answers/fixtures/duplicate_activity_in_flow.json, src/apps/answers/tests/test_answers.py, src/apps/answers/tests/test_answers_arbitrary.py
[M2-2723](https://mindlogger.atlassian.net/browse/M2-2723)
=> M2-2723 Change date return values to timestamps in data export

src/apps/workspaces/crud/user_applet_access.py
https://mindlogger.atlassian.net/browse/M2-3158
=> M2-3158 Check soft exists for respondent list

src/apps/answers/crud/answers.py, src/apps/answers/tests/test_answers.py, src/apps/answers/tests/test_answers_arbitrary.py
=> M2-3237 FIX identifiers: HTTP 500 error

.pre-commit-config.yaml, Makefile, README.md
add a hook to check commits for aws keys
=> Add git-secrets hook

src/apps/answers/service.py, src/consumer.py
https://mindlogger.atlassian.net/browse/M2-3177
=> M2-3177: Add arbitrary session support in consumer

src/apps/activities/crud/activity_history.py
https://mindlogger.atlassian.net/browse/M2-2751
=> M2-2751: Response type for CST

src/apps/alerts/api.py, src/apps/alerts/crud/alert.py
https://mindlogger.atlassian.net/browse/M2-3088
=> M2-3088: Exclude alerts from deleted alerts

src/apps/applets/api/applets.py, src/apps/applets/domain/applet.py, src/apps/applets/router.py, src/apps/applets/service/applet.py, src/apps/invitations/crud.py, src/apps/invitations/services.py, src/apps/workspaces/crud/user_applet_access.py, src/apps/workspaces/service/user_applet_access.py
https://mindlogger.atlassian.net/browse/M2-2959
=> m2-2959: Nickname by applet

src/apps/activities/domain/activity_create.py, src/apps/activities/domain/custom_validation.py, src/apps/applets/tests/test_applet.py, src/apps/applets/tests/test_applet_activity_items.py, src/apps/shared/changes_generator.py
Validation and change generation for reports, fix tests
=> Fix validation and change generation for new reports logic

src/apps/file/api/file.py, src/apps/file/services.py
https://mindlogger.atlassian.net/browse/M2-3171
=> M2-3171: Added presign ep

src/apps/file/api/file.py, src/apps/file/router.py
https://mindlogger.atlassian.net/browse/M2-3171
=> M2-3171: Added presign ep 

src/apps/answers/crud/answers.py, src/apps/answers/domain/answers.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py, src/apps/answers/tests/test_answers_arbitrary.py, src/apps/authentication/api/auth.py, src/apps/authentication/crud.py, src/apps/authentication/deps.py, src/apps/authentication/services/core.py, src/apps/authentication/services/security.py, src/apps/migrate/answers/answer_item_service.py, src/apps/migrate/answers/answer_note_service.py, src/apps/migrate/answers/answer_service.py, src/apps/migrate/data_description/applet_user_access.py, src/apps/migrate/data_description/user_pins.py, src/apps/migrate/services/applet_service.py, src/apps/migrate/services/mongo.py, src/apps/migrate/services/postgres.py, src/apps/shared/domain/custom_validations.py, src/apps/test_data/domain.py, src/apps/users/cruds/user.py, src/apps/users/db/schemas.py, src/apps/users/tests/test_password.py, src/apps/workspaces/crud/user_applet_access.py, src/infrastructure/cache/services.py, src/infrastructure/database/base.py, src/infrastructure/utility/redis_client.py
https://mindlogger.atlassian.net/browse/M2-3280
=> M2-3280 Fix datetime timezone processing

src/apps/applets/crud/applets.py
https://mindlogger.atlassian.net/browse/M2-3292
=> M2-3292 Fix account count on flat list

src/apps/activities/domain/custom_validation.py
https://mindlogger.atlassian.net/browse/M2-3301
=> M2-3301: Fix conditional custom logic validation

src/apps/activities/crud/activity_history.py, src/apps/answers/crud/answers.py, src/apps/answers/service.py
https://mindlogger.atlassian.net/browse/M2-3294
=> M2-3294 Show previous version if current doesn't have answers

src/apps/file/api/file.py, src/infrastructure/utility/cdn_arbitrary.py, src/infrastructure/utility/cdn_client.py
https://mindlogger.atlassian.net/browse/M2-3141
=> M2-3141: Unblock eventloop via file uploading v2

src/apps/migrate/run.py, src/apps/migrate/services/event_service.py
https://mindlogger.atlassian.net/browse/M2-3063
=> M2-3063: Events migration

src/apps/schedule/crud/events.py, src/apps/schedule/service/schedule.py
https://mindlogger.atlassian.net/browse/M2-3370
=> M2-3370: Fixed deletion of individual event

src/apps/activities/crud/activity_history.py, src/apps/answers/crud/answers.py, src/apps/answers/service.py
https://mindlogger.atlassian.net/browse/M2-3294
=> M2-3294: show all versions on default

src/apps/answers/tests/test_answers.py, src/apps/shared/domain/custom_validations.py
https://mindlogger.atlassian.net/browse/M2-3397
=> M2-3397: Zero timestamps

src/apps/answers/tests/test_answers.py, src/apps/workspaces/crud/user_applet_access.py
https://mindlogger.atlassian.net/browse/M2-3418
=> M2-3418: Reviewer alert

src/apps/authentication/api/auth.py, src/apps/authentication/errors.py, src/apps/authentication/services/security.py, src/locale/base.pot
https://mindlogger.atlassian.net/browse/M2-3372
=> M2-3372: Fix email enumeration

src/apps/answers/service.py, src/apps/answers/tests/test_answers.py, src/apps/workspaces/crud/user_applet_access.py
https://mindlogger.atlassian.net/browse/M2-3270
=> M2-3270: Send alert on email

src/apps/migrate/services/mongo.py, src/apps/migrate/services/postgres.py
https://mindlogger.atlassian.net/browse/M2-3448
=> M2 3448 get owner from applet profile

src/apps/migrate/run.py, src/apps/migrate/services/default_event_service.py, src/apps/migrate/services/postgres.py
https://mindlogger.atlassian.net/browse/M2-3268
https://mindlogger.atlassian.net/browse/M2-3269
=> M2-3286: Add default event for activities and flows

src/apps/answers/api.py, src/apps/answers/domain/answers.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py, src/apps/answers/tests/test_answers_arbitrary.py, src/apps/applets/api/applets.py
https://mindlogger.atlassian.net/browse/M2-3184
=> M2-3184: Added items aggregation

src/apps/migrate/run.py, src/apps/migrate/services/mongo.py, src/apps/migrate/services/postgres.py
https://mindlogger.atlassian.net/browse/M2-3411
=> M2 3411 anon users

src/apps/migrate/data_description/applet_user_access.py, src/apps/migrate/services/postgres.py
https://mindlogger.atlassian.net/browse/M2-3391
=> m2-3391: Fix hierarchy

src/apps/file/api/file.py, src/apps/file/domain.py, src/apps/file/router.py, src/apps/file/services.py, src/apps/migrate/answers/run.py, src/apps/shared/domain/types.py
https://mindlogger.atlassian.net/browse/M2-3459
=> M2-3459: Allow null value for private url

src/apps/migrate/services/mongo.py
https://mindlogger.atlassian.net/browse/M2-3433
=> m2-3433: Fix respondents searching for reviewer

src/apps/folders/crud.py, src/apps/folders/test_folder.py
https://mindlogger.atlassian.net/jira/software/c/projects/M2/issues/M2-3473
=> M2-3473: Fixed show of empty folders

src/apps/file/services.py
https://mindlogger.atlassian.net/browse/M2-3459
=> M2-3459: Fixed regexp for legacy urls

src/apps/migrate/services/event_service.py
https://mindlogger.atlassian.net/browse/M2-3471
=> M2-3471 Scheduled events are missing

src/apps/answers/api.py, src/apps/answers/crud/answers.py, src/apps/answers/domain/answers.py, src/apps/answers/service.py
https://mindlogger.atlassian.net/browse/M2-3519
=> m2-3519 Filter by respondent in query params

src/apps/migrate/answers/run.py, src/apps/migrate/services/mongo.py
https://mindlogger.atlassian.net/browse/M2-3411
=> m2-3411: Add guest account

src/apps/invitations/crud.py, src/apps/invitations/fixtures/invitations.json, src/apps/invitations/services.py, src/apps/invitations/test_invite.py
https://mindlogger.atlassian.net/browse/M2-3532
=> m2-3532: Add filter by invitation status

src/apps/invitations/crud.py, src/apps/invitations/services.py
https://mindlogger.atlassian.net/browse/M2-3099
=> m2-3099: Fix filter to encrypted field

src/apps/themes/domain.py
https://mindlogger.atlassian.net/browse/M2-3399
=> m2-3399: fix themes validation

src/apps/authentication/domain/login/public.py, src/apps/invitations/domain.py, src/apps/shared/domain/custom_validations.py, src/apps/users/domain.py, src/infrastructure/database/migrations/versions/2023_09_22_13_49-emails_to_lowercase.py
https://mindlogger.atlassian.net/browse/M2-1768
=> m2-1768: Emails to lowercase

src/infrastructure/database/migrations/versions/2023_09_22_13_49-emails_to_lowercase.py
https://mindlogger.atlassian.net/browse/M2-1768
=> m2-1768: Fix hash emails duplication

src/apps/shared/domain/custom_validations.py, src/apps/users/domain.py
https://mindlogger.atlassian.net/browse/M2-3567
=> m2-3567: Fix password recovery

src/apps/answers/domain/answers.py, src/apps/migrate/answers/answer_item_service.py, src/apps/migrate/answers/run.py
https://mindlogger.atlassian.net/browse/M2-3422
https://mindlogger.atlassian.net/browse/M2-3569
=> M2-3569: Respondent id in answers correct one

src/apps/applets/domain/applet.py, src/apps/migrate/run.py, src/apps/migrate/services/postgres.py
https://mindlogger.atlassian.net/browse/M2-3577
=> m2-3577: Change null themes to default

README.md, src/apps/answers/service.py, src/apps/mailing/static/templates/response_alert_en.html
https://mindlogger.atlassian.net/browse/M2-3542
=> m2-3542: Add domain to template compile kwargs

src/apps/applets/service/applet.py
https://mindlogger.atlassian.net/browse/M2-3584
=> m2-3584: Fix theme search scope

src/apps/migrate/run.py, src/apps/migrate/services/alert_service.py
https://mindlogger.atlassian.net/browse/M2-3453
=> M2-3453: Migrate Alerts

src/apps/migrate/services/mongo.py
https://mindlogger.atlassian.net/browse/M2-3412
=> m2-3412: Fix respondent searching

src/apps/migrate/answers/crud.py, src/apps/migrate/answers/run.py, src/apps/migrate/run.py, src/apps/migrate/services/mongo.py, src/apps/migrate/utilities.py, src/infrastructure/database/migrations_arbitrary/versions/2023_08_11_00_00-arbitrary-tables.py
https://mindlogger.atlassian.net/browse/M2-3506
=> M2-3506: Added migration arguments, M2-3381 Arbitrary

src/apps/answers/crud/answers.py
https://mindlogger.atlassian.net/browse/M2-3631
=> M2-3631 Fix reportability check for answer's activity

Pipfile, Pipfile.lock, src/apps/file/api/file.py, src/apps/file/router.py, src/apps/file/services.py, src/apps/file/storage.py, src/apps/workspaces/service/user_access.py, src/config/__init__.py, src/config/logs.py, src/infrastructure/utility/cdn_client.py
https://mindlogger.atlassian.net/browse/M2-2958
=> M2 2958 logs endpoints

src/apps/migrate/data_description/library_dao.py, src/apps/migrate/services/event_service.py
https://mindlogger.atlassian.net/browse/M2-3471
=> M2-3471: scheduled events are missing

src/apps/workspaces/service/user_access.py
https://mindlogger.atlassian.net/browse/M2-1998
=> M2-1998: Fixed set user access

src/apps/activities/services/activity_item_history.py
https://mindlogger.atlassian.net/browse/M2-3636
=> M2-3636: Copy is_hidden attribute to ActivityItemHistory

src/apps/migrate/answers/run.py, src/apps/workspaces/domain/user_applet_access.py
https://mindlogger.atlassian.net/browse/M2-3569
=> M2-3569: Allow none emails

src/apps/migrate/services/mongo.py
https://mindlogger.atlassian.net/browse/M2-3433
=> M2-3433: Change folder owner id

docker-compose.yaml
https://mindlogger.atlassian.net/browse/M2-3671
=> M2-3671 Fix taskiq worker, scheduler commands

src/apps/applets/api/applets.py, src/apps/migrate/data_description/public_link.py, src/apps/migrate/run.py, src/apps/migrate/services/mongo.py, src/apps/migrate/services/postgres.py, src/apps/schedule/api/schedule.py, src/apps/shared/link.py
https://mindlogger.atlassian.net/browse/M2-3451
=> M2-3451: Public link migration

src/apps/mailing/static/templates/footers/footer_contact_us_en.html
https://mindlogger.atlassian.net/browse/M2-1938
=> M2-1938 Remove “Matter Lab” from email templates

src/apps/answers/domain/answers.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py, src/apps/answers/tests/test_answers_arbitrary.py, src/apps/workspaces/crud/applet_access.py, src/apps/workspaces/db/schemas/user_applet_access.py, src/apps/workspaces/domain/user_applet_access.py
https://mindlogger.atlassian.net/browse/M2-3476
=> M2-3476 Add legacy_profile_id to data export

src/apps/migrate/run.py, src/apps/migrate/services/invitation_service.py
https://mindlogger.atlassian.net/browse/M2-3452
=> M2-3452: Migrate pending invitations

src/apps/migrate/services/event_service.py
https://mindlogger.atlassian.net/browse/M2-3471
=> M2-3471: Fix for individual events

src/apps/answers/tests/test_answers.py, src/apps/answers/tests/test_answers_arbitrary.py, src/apps/migrate/data_description/applet_user_access.py, src/apps/migrate/services/mongo.py, src/apps/migrate/services/postgres.py
https://mindlogger.atlassian.net/browse/M2-3678
=> M2-3678: appletProfile._id to meta

src/apps/shared/ordering.py, src/apps/shared/query_params.py
https://mindlogger.atlassian.net/browse/M2-723
=> M2-723 Sort in ascending order fixed

src/apps/answers/filters.py, src/apps/answers/tests/test_answers.py, src/apps/answers/tests/test_answers_arbitrary.py
https://mindlogger.atlassian.net/browse/M2-3704
=> M2-3704: Change default value

src/apps/file/api/file.py, src/apps/file/domain.py, src/apps/file/services.py, src/apps/file/storage.py, src/apps/file/test_file.py, src/infrastructure/dependency/cdn.py, src/infrastructure/dependency/presign_service.py, src/infrastructure/utility/cdn_arbitrary.py, src/infrastructure/utility/cdn_client.py, src/infrastructure/utility/cdn_config.py
https://mindlogger.atlassian.net/browse/M2-3682
=> M2-3682: Fix bucket settings

src/apps/migrate/run.py, src/apps/migrate/services/alert_service.py, src/apps/migrate/services/postgres.py
https://mindlogger.atlassian.net/browse/M2-3666
=> M2-3666: added version to alerts migration

src/apps/alerts/domain.py, src/apps/applets/domain/applet.py, src/apps/migrate/run.py, src/apps/migrate/services/alert_service.py, src/apps/migrate/services/event_service.py, src/apps/migrate/services/postgres.py
https://mindlogger.atlassian.net/browse/M2-3471
https://mindlogger.atlassian.net/browse/M2-3657
=> M2-3471: scheduled events are missing. M2-3657: Cross-day Events

src/apps/migrate/run.py, src/apps/migrate/services/postgres.py
https://mindlogger.atlassian.net/browse/M2-3569
=> M2 3569 fix empty question

src/apps/file/api/file.py, src/apps/file/services.py, src/infrastructure/logger.py
https://mindlogger.atlassian.net/browse/M2-3732
=> M2-3732: Logger for log endpoints

src/apps/file/api/file.py, src/apps/file/domain.py, src/apps/file/services.py
https://mindlogger.atlassian.net/browse/M2-3761
=> M2-3761: File size return on upload check

src/apps/migrate/services/default_event_service.py, src/apps/migrate/services/postgres.py
https://mindlogger.atlassian.net/browse/M2-3736
=> M2-3736: Added new logic for default AA events

src/apps/migrate/run.py, src/apps/migrate/services/mongo.py
https://mindlogger.atlassian.net/browse/M2-3739
=> M2 3739 fix missing roles

src/apps/migrate/run.py, src/apps/migrate/services/mongo.py, src/apps/migrate/services/postgres.py
https://mindlogger.atlassian.net/browse/M2-3433
=> M2 3433 missing shared folders

src/apps/applets/service/applet.py
https://mindlogger.atlassian.net/browse/M2-2467
=> M2-2467 Incorrect applet version increment fixed.

src/apps/schedule/api/schedule.py, src/apps/workspaces/service/check_access.py
https://mindlogger.atlassian.net/browse/M2-2445
=> M2-2445 viewing General calendar fixed

src/apps/themes/api/themes.py, src/apps/themes/crud.py, src/apps/themes/service.py
https://mindlogger.atlassian.net/browse/M2-3810
=> M2-3810: Fix themes count

src/apps/migrate/services/mongo.py
Invert values for isVis attr (true -> false, false -> true) in migration scripts for correct processing values in jsonld convertor. It is required for correct logic to show hidden/not hidden activities/items after migration.
=> M2-3307: Add logic to convert bool isVis for correct values for jsonld_converter

src/apps/migrate/services/mongo.py
https://mindlogger.atlassian.net/browse/M2-3739
=> M2-3739: Fix manager-reviewer mismatch

src/apps/migrate/services/mongo.py
https://mindlogger.atlassian.net/browse/M2-3839
=> M2-3839: Fix empty logic

src/apps/migrate/services/invitation_service.py
https://mindlogger.atlassian.net/browse/M2-3452
=> M2-3452 fixes in pending invitations

src/apps/migrate/run.py, src/apps/migrate/services/mongo.py, src/apps/migrate/services/postgres.py
https://mindlogger.atlassian.net/browse/M2-3856
=> M2 3856 clean folder applet

src/apps/migrate/services/event_service.py
https://mindlogger.atlassian.net/browse/M2-3838
=> M2-3838: Timer for events is not migrated correctly

src/apps/migrate/data_description/library_dao.py, src/apps/migrate/run.py, src/apps/migrate/services/mongo.py, src/apps/migrate/services/postgres.py, src/apps/migrate/utilities.py
https://mindlogger.atlassian.net/browse/M2-3392
=> M2-3392: Fix theme setting to applets

src/apps/workspaces/service/check_access.py
https://mindlogger.atlassian.net/browse/M2-3869
=> M2-3869: Add reviewer to allow roles

src/apps/file/api/file.py, src/apps/users/services/user.py
https://mindlogger.atlassian.net/browse/M2-3883
=> M2-3883: Change search user log files using email instead of guid

src/apps/file/services.py
https://mindlogger.atlassian.net/browse/M2-3893
=> M2-3893: Change sort key

src/apps/jsonld_converter/service/document/field.py
https://mindlogger.atlassian.net/browse/M2-3191
=> M2-3191 The slider min max label fixed

src/apps/migrate/services/mongo.py
https://mindlogger.atlassian.net/browse/M2-3481
=> M2-3481: Fix pins migration inside folders

src/apps/file/router.py
https://mindlogger.atlassian.net/browse/M2-3906
=> M2-3906: Change query to path

src/apps/invitations/services.py, src/apps/mailing/static/templates/footers/footer_info_fr.html, src/apps/mailing/static/templates/invitation_new_user_fr.html, src/apps/mailing/static/templates/invitation_registered_user_fr.html
https://mindlogger.atlassian.net/browse/M2-3514
=> M2-3514 A letter in French has been added to a Manager Invitation.

src/apps/migrate/services/event_service.py
https://mindlogger.atlassian.net/browse/M2-3945
https://mindlogger.atlassian.net/browse/M2-3931
=> M2-3945, M2-3931: fixes for events

src/apps/schedule/service/schedule.py
https://mindlogger.atlassian.net/browse/M2-3919
=> M2-3919 Bug in the individual plan import fixed

src/apps/migrate/services/event_service.py
https://mindlogger.atlassian.net/browse/M2-3931
=> M2-3931: Backend: PMHSA11+: Refresh error. Fix for events

src/apps/migrate/services/mongo.py
https://mindlogger.atlassian.net/browse/M2-3960
=> m2-3960: Fix empty activity types

src/apps/migrate/data_description/applet_user_access.py, src/apps/migrate/services/mongo.py
https://mindlogger.atlassian.net/browse/M2-3983
=> m2-3983: Fix generated secret user id for manager

src/apps/migrate/services/mongo.py
https://mindlogger.atlassian.net/browse/M2-3896
=> M2-3896: remove unnecessary nickname generation

src/apps/migrate/services/mongo.py
https://mindlogger.atlassian.net/browse/M2-3990
=> M2-3990: creatorid in extra_fields

src/apps/migrate/run.py
https://mindlogger.atlassian.net/browse/M2-3991
=> M2-3991: extra applets for library top 25

src/apps/mailing/static/templates/invitation_new_user_en.html, src/apps/mailing/static/templates/invitation_new_user_fr.html, src/apps/mailing/static/templates/invitation_registered_user_en.html, src/apps/mailing/static/templates/invitation_registered_user_fr.html
https://mindlogger.atlassian.net/browse/M2-4020
=> M2-4020: Replace link to userguide in the email templates

src/apps/file/api/file.py, src/apps/file/domain.py, src/apps/file/services.py
https://mindlogger.atlassian.net/browse/M2-4047
=> m2-4047: Allow null at presign endpoint

src/apps/answers/crud/answers.py, src/apps/answers/deps/preprocess_arbitrary.py, src/apps/answers/service.py, src/apps/workspaces/api.py, src/apps/workspaces/domain/workspace.py, src/apps/workspaces/service/workspace.py
https://mindlogger.atlassian.net/browse/M2-4039
=> m2-4039: Get answer last answer created_at as last seen

src/apps/invitations/services.py, src/apps/workspaces/crud/user_applet_access.py, src/apps/workspaces/service/user_applet_access.py
https://mindlogger.atlassian.net/browse/M2-4017
=> M2-4017: Remove nickname combination from firstname and lastname when joined by private link 

Pipfile, Pipfile.lock, src/apps/answers/fixtures/arbitrary_server_answers.json, src/apps/migrate/answers/answer_note_service.py, src/apps/migrate/services/mongo.py, src/apps/workspaces/commands/__init__.py, src/apps/workspaces/commands/arbitrary_server.py, src/apps/workspaces/constants.py, src/apps/workspaces/crud/workspaces.py, src/apps/workspaces/db/schemas/user_workspace.py, src/apps/workspaces/domain/workspace.py, src/apps/workspaces/errors.py, src/apps/workspaces/service/workspace.py, src/cli.py, src/infrastructure/database/migrations/versions/2023_11_11_19_02-encrypt_workspace_arbitrary_fields.py
https://mindlogger.atlassian.net/browse/M2-3889
=> Hotfix m2 3889 arbitrary db excryption dev

src/apps/mailing/static/templates/invitation_new_user_en.html, src/apps/mailing/static/templates/invitation_registered_user_en.html
https://mindlogger.atlassian.net/browse/M2-4023
=> M2-4023 "Go to..." button is horizontally aligned in the invitation email

src/apps/workspaces/crud/user_applet_access.py, src/apps/workspaces/test_workspaces.py
https://mindlogger.atlassian.net/browse/M2-4171
=> M2-4171:  Fix nickname for managers' respondent (fix to release branch)

src/apps/workspaces/crud/user_applet_access.py, src/apps/workspaces/service/user_applet_access.py
https://mindlogger.atlassian.net/browse/M2-4171
=> M2-4171: transfer ownership nickname fix

src/apps/applets/fixtures/applet_user_accesses.json, src/apps/workspaces/api.py, src/apps/workspaces/test_workspaces.py
https://mindlogger.atlassian.net/browse/M2-4196
=> M2-4196: Check manager role on retrieve respondent details

src/apps/schedule/domain/schedule/requests.py
https://mindlogger.atlassian.net/browse/M2-3912
=> M2-3912: Cross-day Event

src/apps/workspaces/crud/user_applet_access.py, src/apps/workspaces/service/user_applet_access.py
https://mindlogger.atlassian.net/browse/M2-4056?focusedCommentId=16175
=> M2-4056: nick remove from meta on create n invite

src/apps/mailing/static/templates/invitation_new_user_en.html, src/apps/mailing/static/templates/invitation_new_user_fr.html, src/apps/mailing/static/templates/invitation_registered_user_en.html, src/apps/mailing/static/templates/invitation_registered_user_fr.html
https://mindlogger.atlassian.net/browse/M2-4050
=> M2-4050 The "Bo to..." button style of email fixed.

src/apps/answers/service.py
Fix session selection on answer exist check
=> M2-3889: Add session selector on answer check

src/infrastructure/database/migrations_arbitrary/env.py
https://mindlogger.atlassian.net/browse/M2-4223
=> M2-4223: Add decryption alembic settings in migration

src/apps/activities/services/activity.py, src/apps/activity_flows/service/flow.py
https://mindlogger.atlassian.net/browse/M2-4117
=> M2-4117: create default event for individual schedule

src/apps/answers/service.py
https://mindlogger.atlassian.net/browse/M2-4239
=> M2-4239: Reviewer access to unassigned respondents fix

src/infrastructure/database/migrations_arbitrary/env.py
Add logging to arbitrary server migration runner and add filter on empty strings in database_uri column
=> M2-3889: Arbitrary migration log, and filter on empty string as uri

src/apps/applets/crud/applets.py, src/infrastructure/database/migrations/versions/2023_11_29_17_08-cron_removing_expired_blacklisted_tokens.py
https://mindlogger.atlassian.net/browse/M2-4193
=> M2-4193: unique applet name filter by is_deleted

src/apps/invitations/crud.py
https://mindlogger.atlassian.net/browse/M2-4300
=> M2-4300: return nickname for invited users list

src/apps/answers/domain/answers.py, src/apps/answers/tests/test_answers.py, src/apps/answers/tests/test_answers_arbitrary.py
https://mindlogger.atlassian.net/browse/M2-3664
=> M2-3664: Answer create contract item_ids required

src/apps/workspaces/service/user_applet_access.py, src/infrastructure/database/migrations/versions/2023_12_04_15_45-remove_nickname_from_guest_account.py
https://mindlogger.atlassian.net/browse/M2-4220
=> M2-4220: remove nickname from guest account

src/apps/activities/crud/activity_history.py, src/apps/activities/services/activity_history.py, src/apps/answers/service.py, src/apps/applets/service/applet_history_service.py
https://mindlogger.atlassian.net/browse/M2-4249
=> M2-4249: Add filter to non perf tasks activities

src/apps/schedule/api/schedule.py
https://mindlogger.atlassian.net/browse/M2-2936
=> M2-2936 Notification messages for changed schedule updated.

src/apps/activities/crud/activity_history.py, src/apps/answers/service.py
https://mindlogger.atlassian.net/browse/M2-2759
=> M2-2759 Behavior when sending request with incorrect activityId fixed

src/apps/schedule/crud/events.py, src/apps/schedule/service/schedule.py
https://mindlogger.atlassian.net/browse/M2-4367
=> M2-4367: Delete all events on applet transfer

src/apps/activities/crud/activity_history.py, src/apps/activities/services/activity.py, src/apps/answers/tests/test_answers_arbitrary.py
- M2-4345: Remove legacy logic to identify performance task
- M2-4345: remuve redundant query
=> M2 4345 unify logic to filter performance tasks

src/apps/migrate/services/activity_item_history_service.py, src/apps/migrate/services/activity_service.py, src/apps/migrate/utilities.py, src/infrastructure/database/migrations/versions/2023_12_13_07_14-update_created_at_from_updated_at.py
- M2-4381: Add migration to correct created_at in activity_histories and activity_item_histories
- M2-4381: Fix issues in migration scripts after changes in models
=> M2 4381 incorrect created at in migrated activity items and activity item histories

src/apps/answers/service.py
https://mindlogger.atlassian.net/browse/M2-3755
=> M2-3755 Verifying activity_id and respondent_id added to /latest_report

src/apps/logs/domain/notification.py
https://mindlogger.atlassian.net/browse/M2-1896
=> M2-1896 The createdAt property added to every notification-log record

src/apps/schedule/crud/events.py, src/apps/schedule/service/schedule.py
https://mindlogger.atlassian.net/browse/M2-4367
=> M2 4367 fix event deletation

src/apps/workspaces/errors.py
https://mindlogger.atlassian.net/browse/M2-2696
=> M2-2696 Error text in the Edit Respondent form updated.

src/apps/answers/service.py
https://mindlogger.atlassian.net/browse/M2-3755
=> M2-3755 Error messages updated.

src/apps/activities/commands/__init__.py, src/apps/activities/commands/reindex_items.py, src/cli.py
https://mindlogger.atlassian.net/browse/M2-3859
=> M2-3859: Cli for reindex activity items

src/apps/migrate/answers/answer_item_service.py, src/apps/migrate/answers/run.py
https://mindlogger.atlassian.net/browse/M2-4080
=> M2 4080 fix versions

src/apps/answers/service.py, src/apps/answers/tests/test_answers_arbitrary.py, src/apps/shared/exception.py
https://mindlogger.atlassian.net/browse/M2-3755
=> M2-3755 Error messages hotfix

src/apps/logs/crud/notification.py, src/apps/logs/tests.py
https://mindlogger.atlassian.net/browse/M2-4444
=> M2-4444: Use previous value for logs and fix filter

src/infrastructure/database/migrations/versions/2023_12_21_10_30-create_default_theme.py
https://mindlogger.atlassian.net/browse/M2-4440
=> M2-4440 The migration for first theme added.

src/apps/themes/db/schemas.py, src/infrastructure/database/migrations/versions/2023_12_21_10_30-create_default_theme.py
https://mindlogger.atlassian.net/browse/M2-4440
=> M2-4440 The create_default_theme migration updated.

src/apps/shared/commands/__init__.py, src/apps/shared/commands/domain.py, src/apps/shared/commands/patch.py, src/apps/shared/commands/patch_commands.py, src/apps/shared/commands/patches/__init__.py, src/apps/shared/commands/patches/sample.sql, src/apps/shared/commands/patches/sample_arbitrary.py, src/apps/shared/commands/patches/sample_manage_session_arbitrary.py, src/apps/shared/commands/patches/slider_tickmark_label.py, src/cli.py
https://mindlogger.atlassian.net/browse/M2-3781
https://mindlogger.atlassian.net/browse/M2-4280
=> M2-4280: hotfix to main

src/apps/invitations/services.py, src/apps/themes/domain.py, src/infrastructure/database/migrations/versions/2023_12_21_10_30-create_default_theme.py
https://mindlogger.atlassian.net/browse/M2-1329
=> M2-1329 Bug with language of the Invite Email for reviewer fixed

src/apps/applets/tests/test_applet_activity_items.py
https://mindlogger.atlassian.net/browse/M2-4506
=> M2-4506: API test for activity items item flow, section, scores.

src/apps/logs/crud/notification.py, src/apps/logs/tests.py
https://mindlogger.atlassian.net/browse/M2-4395
=> M2-4395: Allow empty arrays

src/apps/logs/crud/notification.py, src/apps/logs/tests.py
https://mindlogger.atlassian.net/browse/M2-4395
=> M2-4395: Removed implicit conversion to boolean

src/apps/mailing/static/templates/footers/footer_contact_us_en.html
https://mindlogger.atlassian.net/browse/M2-4561
=> M2-4561: change year to 2024 in the emails

src/apps/invitations/services.py, src/apps/mailing/static/templates/invitation_new_user_en.html, src/apps/mailing/static/templates/invitation_new_user_fr.html, src/apps/mailing/static/templates/invitation_registered_user_en.html, src/apps/mailing/static/templates/invitation_registered_user_fr.html
https://mindlogger.atlassian.net/browse/M2-4535
=> M2-4535: add last_name to emails

src/apps/activities/services/activity_item_change.py, src/apps/activities/tests/unit/test_activity_item_change.py
https://mindlogger.atlassian.net/browse/M2-4441
=> M2-4441: Applet version changes: removed item is not tracked

src/apps/activities/errors.py, src/apps/applets/domain/applet_create_update.py, src/apps/applets/tests/test_applet.py, src/apps/applets/tests/test_applet_activity_items.py
https://mindlogger.atlassian.net/browse/M2-4739
=> M2-4739: flow item key check existence

README.md, src/apps/applets/crud/applets.py, src/apps/users/commands/__init__.py, src/apps/users/commands/token.py, src/apps/workspaces/crud/user_applet_access.py, src/cli.py
https://mindlogger.atlassian.net/browse/M2-4507
=> M2 4507 ordering

src/apps/activities/domain/activity_create.py, src/apps/activities/domain/activity_update.py, src/apps/activities/domain/custom_validation.py, src/apps/activities/errors.py, src/apps/activities/tests/unit/test_activity_item_change.py, src/apps/applets/tests/test_applet_activity_items.py
https://mindlogger.atlassian.net/browse/M2-4690
=> M2-4690:item option id not allow duplicate

src/apps/transfer_ownership/service.py, src/apps/transfer_ownership/tests.py, src/apps/workspaces/crud/user_applet_access.py
https://mindlogger.atlassian.net/browse/M2-4791
=> M2-4791: tranfer ownership functionality update

src/apps/applets/crud/applets.py, src/apps/applets/tests/conftest.py, src/apps/applets/tests/test_applet.py, src/apps/applets/tests/test_applet_link.py, src/apps/users/fixtures/users.json, src/apps/workspaces/api.py, src/apps/workspaces/crud/applet_access.py, src/apps/workspaces/crud/user_applet_access.py, src/apps/workspaces/crud/workspaces.py, src/apps/workspaces/domain/workspace.py, src/apps/workspaces/errors.py, src/apps/workspaces/service/user_access.py, src/apps/workspaces/service/user_applet_access.py, src/apps/workspaces/service/workspace.py, src/apps/workspaces/tests/test_workspaces.py, src/apps/workspaces/tests/unit/domain/test_workspace_arbitrary.py
- M2-4500: fix sqlalchemy warnings
- M2-4500: Add more tests for workspaces:
=> M2 4500 tests workspaces

src/apps/activities/domain/activity.py, src/apps/activities/services/activity.py, src/apps/activities/services/activity_item.py, src/apps/applets/tests/test_applet.py
https://mindlogger.atlassian.net/browse/M2-4852
=> m2-4852: add item_count to base_info APIs

src/apps/applets/api/applets.py, src/apps/applets/service/applet.py, src/apps/invitations/api.py, src/apps/subjects/api.py, src/apps/subjects/crud/subject.py, src/apps/subjects/crud/subject_respondent.py, src/apps/subjects/domain.py, src/apps/subjects/router.py, src/apps/subjects/services/subjects.py, src/apps/subjects/tests.py
https://mindlogger.atlassian.net/browse/M2-4796
=> m2-4796: Assign unassign respondents in shell account

src/apps/transfer_ownership/api.py
https://mindlogger.atlassian.net/browse/M2-4880
=> M2-4880: keep events after transfer ownership

src/apps/activities/domain/activity_create.py, src/apps/activities/domain/activity_update.py, src/apps/activities/domain/custom_validation.py, src/apps/activities/errors.py, src/apps/activities/tests/unit/test_activity_item_change.py, src/apps/applets/tests/test_applet_activity_items.py
This reverts commit 61a98c35a8f81fad0708ff8ca14f111fb8323a4d, reversing changes made to ad7befdc22a2fc947ec7c08f572a37075c2e1581.
=> Revert "Merge pull request #1003 from ChildMindInstitute/M2-4690"

src/apps/answers/crud/answers.py, src/apps/answers/domain/answers.py, src/apps/answers/tests/test_answers.py, src/apps/answers/tests/test_answers_arbitrary.py
https://mindlogger.atlassian.net/browse/M2-4846
=> M2-4846 Add "client" to answers export data

src/apps/invitations/services.py, src/apps/invitations/test_invite.py, src/apps/subjects/api.py, src/apps/subjects/crud/subject.py, src/apps/subjects/domain.py, src/apps/subjects/router.py, src/apps/subjects/services/subjects.py, src/apps/subjects/tests.py, src/apps/workspaces/service/check_access.py
https://mindlogger.atlassian.net/browse/M2-4627
=> M2 4627 subject edit endpoint

src/apps/schedule/crud/events.py, src/apps/schedule/service/schedule.py
resolves: [M2-4756](https://mindlogger.atlassian.net/browse/M2-4756),  [M2-3434](https://mindlogger.atlassian.net/browse/M2-3434)
- Fix deleting events when activities or flows are deleted. 
- Fix successfully deleting default event when individual events exist.
[PR](https://github.com/ChildMindInstitute/mindlogger-backend-refactor/pull/906) for [M2-3434](https://mindlogger.atlassian.net/browse/M2-3434) caused [M2-4756](https://mindlogger.atlassian.net/browse/M2-4756). This PR, basically, implements another way of fix for [M2-3434](https://mindlogger.atlassian.net/browse/M2-3434)
Test of all the functionality of events by QA engineers.
[M2-4756]: https://mindlogger.atlassian.net/browse/M2-4756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> M2-4756: M2-3434: fix deleting events

src/apps/applets/tests/test_applet_folder.py, src/apps/folders/api.py, src/apps/folders/crud.py, src/apps/folders/fixtures/folders.json, src/apps/folders/service.py, src/apps/folders/test_folder.py
- M2-4498: Remove redundant atomic
- M2-4498: Add missing API tests for folder
=> M2 4498 tests for folders

src/apps/answers/crud/answers.py, src/apps/answers/domain/answers.py, src/apps/answers/filters.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py, src/apps/answers/tests/test_answers_arbitrary.py, src/apps/workspaces/crud/applet_access.py, src/apps/workspaces/db/schemas/user_applet_access.py, src/apps/workspaces/domain/user_applet_access.py
resolves: M2-4631
https://mindlogger.atlassian.net/browse/M2-4631
Rework answer export EP implementing subject instead of respondent
=> M2-4631 Update answers export with subject data

src/apps/answers/domain/answers.py
resolves: [M2-5000](https://mindlogger.atlassian.net/browse/M2-5000)
Fix "client" value format for data export
[M2-5000]: https://mindlogger.atlassian.net/browse/M2-5000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> M2-5000 Fix answers export "client" type

src/apps/alerts/ws_api.py
resolves: M2-4882
Fix error message " 'websocket.close', after sending 'websocket.close'".
M2-5040
=> M2-4882: remove redundant close in  alerts websocket

src/apps/answers/api.py, src/apps/answers/crud/answer_items.py, src/apps/answers/crud/answers.py, src/apps/answers/domain/answers.py, src/apps/answers/filters.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py, src/apps/applets/fixtures/applet_user_accesses.json, src/apps/subjects/crud/subject.py, src/apps/subjects/services/subjects.py, src/apps/workspaces/crud/applet_access.py, src/apps/workspaces/service/check_access.py
resolves: M2-4635
Datavis changes for subject's answers
=> M2-4635: Dataviz for multiinformant feature

src/apps/answers/crud/answers.py, src/apps/answers/service.py, src/apps/shared/filtering.py, src/apps/workspaces/crud/user_applet_access.py, src/apps/workspaces/domain/workspace.py, src/apps/workspaces/filters.py
resolves: M2-4630
https://mindlogger.atlassian.net/browse/M2-4630
Implementation of group by user id for full and shell accounts
=> M2 4630 Workspace respondent list fix grouping for full and shell accounts

conftest.py, pyproject.toml, src/apps/activities/crud/reusable_item_choices.py, src/apps/answers/crud/notes.py, src/apps/authentication/services/security.py, src/apps/folders/crud.py, src/apps/shared/passlib.py, src/apps/themes/crud.py, src/apps/users/api/password.py, src/apps/users/api/users.py, src/apps/users/cruds/user.py, src/apps/users/cruds/user_device.py, src/apps/users/domain.py, src/apps/users/errors.py, src/apps/users/services/core.py, src/apps/users/services/user.py, src/apps/users/services/user_device.py, src/apps/users/tests/fixtures/users.py, src/apps/users/tests/test_user.py, src/apps/users/tests/unit/test_user_crud.py, src/apps/users/tests/unit/test_user_devices_service.py, src/apps/users/tests/unit/test_user_domain.py, src/apps/users/tests/unit/test_user_service.py, src/config/anonymous_respondent.py, src/config/superuser.py, src/infrastructure/database/crud.py
resolves: [M2-5009](https://mindlogger.atlassian.net/browse/M2-5009)
Add tests for services and cruds for **users** app to increase project tests coverage within epic [M2-4939](https://mindlogger.atlassian.net/browse/M2-4939)
Implemented small refactoring during the tests. Moved logic to create user from api to the service.
[M2-4962](https://mindlogger.atlassian.net/browse/M2-4962), [M2-4964](https://mindlogger.atlassian.net/browse/M2-4964)
[M2-5009]: https://mindlogger.atlassian.net/browse/M2-5009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[M2-4939]: https://mindlogger.atlassian.net/browse/M2-4939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[M2-4962]: …
=> M2 5009 unit tests for users cruds services

.github/workflows/tests.yaml
resolves: M2-4834
Run automated tests when open a pull request
=> Adding github action workflow to run tests on pull requests

src/apps/schedule/api/schedule.py, src/apps/schedule/crud/events.py, src/apps/schedule/service/schedule.py
resolves: M2-4894, M2-5082
M2-4894 : Push notification for default event change should not be sent to a respondent with individual schedule 
M2-5082 :  Deleting all default schedules should not affect individual schedules
=> M2-4894: M2-5082: Push notification recipient fix, deleting all should keep individual fix

src/apps/subjects/api.py, src/apps/subjects/domain.py, src/apps/subjects/fixtures/subjects.json, src/apps/subjects/router.py, src/apps/subjects/tests.py, src/apps/workspaces/crud/applet_access.py, src/apps/workspaces/service/check_access.py, src/apps/workspaces/tests/test_workspaces.py
resolves: M2-4622
https://mindlogger.atlassian.net/browse/M2-4622
Workaround for stage 1 of multiingormant
=> M2-4622: Workaround for subject details

src/apps/workspaces/crud/user_applet_access.py
resolves: M2-4630
Filter soft deleted subjects
=> m2-4630: Soft delete

src/apps/activities/services/activity_item.py
resolves: M2-5213
Update base_info API to include only visible items in item_count
=> M2-5213: item_count include only visible items

src/apps/mailing/static/templates/response_alert_en.html
resolves: M2-5155
Update response alert email copy
=> M2-5155: Update response alert email copy

src/apps/users/tests/unit/test_user_service.py
resolves: [M2-4964](https://mindlogger.atlassian.net/browse/M2-4964)
Return missing tests for users app
[M2-4964]: https://mindlogger.atlassian.net/browse/M2-4964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> M2-4964: Return missing tests for users

src/apps/file/router.py, src/apps/file/test_file.py
resolves: [M2-4903](https://mindlogger.atlassian.net/browse/M2-4903)
Updated swagger documentation, renamed urls for consistence.
[M2-4903]: https://mindlogger.atlassian.net/browse/M2-4903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> M2-4903: Update swagger documentation

src/apps/activities/tests/unit/test_activity_item_change.py, src/apps/applets/tests/test_applet.py
resolves: M2-5236
Changing test for base_info APIs
Relates to [M2-5213](https://mindlogger.atlassian.net/browse/M2-5213)
[M2-5213]: https://mindlogger.atlassian.net/browse/M2-5213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> M2-5236: test change for base_info APIs

src/apps/mailing/static/templates/transfer_ownership_registered_user_en.html, src/apps/mailing/static/templates/transfer_ownership_unregistered_user_en.html, src/apps/transfer_ownership/service.py, src/apps/users/db/schemas.py, src/apps/users/domain.py, src/apps/users/tests/unit/test_user_crud.py, src/apps/users/tests/unit/test_user_domain.py
resolves: M2-5156, M2-5157
Update copy for transfer ownership email
Added a method to simplify getting the user full name
| Registered | Unregistered |
| --------- | ------- |
| <img width="707" alt="Screenshot 2024-02-09 at 11 42 35" src="https://github.com/ChildMindInstitute/mindlogger-backend-refactor/assets/85007/78d37a0d-9652-4a01-8eb6-6c5cacae2eff"> | <img width="712" alt="Screenshot 2024-02-09 at 11 59 05" src="https://github.com/ChildMindInstitute/mindlogger-backend-refactor/assets/85007/3d93d58d-ffa1-4bc3-9619-9f2466f8e4c4"> |
=> M2-5156, M2-5157: Update copy for transfer ownership email

src/apps/invitations/api.py, src/apps/invitations/crud.py, src/apps/invitations/services.py, src/apps/invitations/test_invite.py
resolves: M2-5252
Disallow to send “Convert shell account invite” to the same email more than 1 time
=> M2-5252: Check email before invitations

src/apps/invitations/crud.py, src/apps/invitations/domain.py
resolves: M2-5256
Change source of secret id for EP invitation get by key
=> M2-5265: Change source for secret id

src/apps/workspaces/crud/user_applet_access.py, src/apps/workspaces/domain/user_applet_access.py, src/apps/workspaces/tests/test_workspaces.py
resolves: M2-5263
Change nickname and secret source for respondent access method
=> m2-5263: Change nickname and secret source for respondent access method

src/apps/applets/api/applets.py, src/apps/shared/commands/patch_commands.py, src/apps/shared/commands/patches/m2_4611_add_answer_subjects.py, src/apps/subjects/services/subjects.py, src/apps/users/tests/test_reencrypt_user_answers.py, src/apps/workspaces/service/user_applet_access.py
resolves: [M2-5253](https://mindlogger.atlassian.net/browse/M2-5253)
Fix automatic respondent creation for manager role, move respondent subject creation to role creation
[M2-5253]: https://mindlogger.atlassian.net/browse/M2-5253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> M2-5253 Fix automatic respondent creation for manager role

src/apps/applets/service/applet.py, src/apps/subjects/services/subjects.py, src/config/anonymous_respondent.py
resolves: [M2-5255](https://mindlogger.atlassian.net/browse/M2-5255)
[M2-5255]: https://mindlogger.atlassian.net/browse/M2-5255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> M2-5255 Fix anonymous respondent creation

src/apps/applets/service/applet.py, src/apps/users/services/user.py
resolves: [M2-5204](https://mindlogger.atlassian.net/browse/M2-5204)
Fix bug with creating applet
[M2-5204]: https://mindlogger.atlassian.net/browse/M2-5204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> M2-5204: Make applet_id optional with None

src/apps/answers/crud/answers.py, src/apps/answers/service.py, src/apps/applets/tests/fixtures/applets.py, src/apps/subjects/api.py, src/apps/subjects/domain.py, src/apps/subjects/tests/tests.py, src/apps/workspaces/api.py
resolves: [M2-5312](https://mindlogger.atlassian.net/browse/M2-5312)
[M2-5312]: https://mindlogger.atlassian.net/browse/M2-5312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> M2-5312 Add lastSeen date to subject details

src/apps/workspaces/crud/user_applet_access.py, src/apps/workspaces/tests/test_workspaces.py
resolves: M2-5384
Fix respondent list for shell accounts
=> M2-5384: Change filter for owner applets

src/apps/subjects/tests/tests.py, src/apps/workspaces/service/check_access.py
resolves: M2-5385
Fix rights checking for non inviters
=> Update role checking for subject retrieve

src/apps/workspaces/api.py, src/apps/workspaces/tests/test_workspaces.py
resolves: M2-5353
Fix for 500 error if subject does not exists
=> M2-5353: Check respondent existence on update

.env.default, .github/workflows/tests.yaml, README.md
resolves: [M2-5284](https://mindlogger.atlassian.net/browse/M2-5284)
Update README file with more organized sections and contents
[M2-5284]: https://mindlogger.atlassian.net/browse/M2-5284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update README file organizing sections and contents

src/apps/workspaces/crud/user_applet_access.py, src/apps/workspaces/tests/test_workspaces.py
resolves: M2-5456
Fix subject status in respondent list
=> M2-5456: Check invited subjects list len

src/apps/mailing/static/templates/transfer_ownership_registered_user_en.html
🔗 [Jira Ticket M2-5342](https://mindlogger.atlassian.net/browse/M2-5342)
Updates the button text to read: "Click here to accept this invitation"
=> M2-5342: Update button copy on transfer template

src/apps/workspaces/crud/user_applet_access.py, src/apps/workspaces/domain/workspace.py, src/apps/workspaces/tests/test_workspaces.py
resolves: M2-5520
https://mindlogger.atlassian.net/browse/M2-5520
=> M2-5520: Change subquery for invitation status

src/apps/invitations/api.py, src/apps/invitations/services.py, src/apps/invitations/test_invite.py, src/apps/subjects/crud/subject.py, src/apps/subjects/db/schemas.py, src/apps/subjects/services/subjects.py, src/infrastructure/database/migrations/versions/2024_02_08_18_28-add_subjects.py
resolves: M2-5519
https://mindlogger.atlassian.net/browse/M2-5519
=> Fix secret id check

src/apps/mailing/static/templates/invitation_registered_user_en.html, src/apps/mailing/static/templates/invitation_registered_user_fr.html
resolves: M2-5158
Fix copy for button in invite registered user:
**Create your account and get started** → **Get started**
Spec:
=> M2-5158: Fix copy for button in invite registered user

.github/pull_request_template.md
🔗 [Jira Ticket M2-5512](https://mindlogger.atlassian.net/browse/M2-5512)
This PR updates the [GitHub pull request description template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates#pull-request-templates) template to an updated format as agreed upon during team's technical talks. 
GitHub will start using this as this repository's pull request template once this is merged to the default branch (`develop`).
- an updated PR template
=> M2-5512: updates PR template format

src/apps/mailing/static/templates/transfer_ownership_unregistered_user_en.html
resolves: M2-5344
Update email welcome message for transfer ownership unregistered user
Spec:
=> M2-5344: Update email welcome message for transfer ownership unregistered user

.env.default, LICENSE.MD, README.md
🔗 [Jira Ticket M2-5284](https://mindlogger.atlassian.net/browse/M2-5284)
Update README
* Adds sections similar to Web, Admin and Mobile app README's
* Added Table of Contents due to length of document
* Added missing `LICENSE.md`
* Removed numbered sections for easier editing without a markdown editor
* Add more detail to Run Locally section
* Add missing environment variables to table
* Add comment about Python 3.10
=> M2-5284: update README

src/apps/subjects/domain.py, src/apps/subjects/services/subjects.py, src/apps/transfer_ownership/service.py, src/apps/transfer_ownership/tests.py, src/apps/workspaces/service/user_applet_access.py
resolves: M2-5483
Fix subject creation for accepting transfer ownership
=> M2-5483: Change subject creation on transfer ownership

src/apps/applets/commands/applet_ema.py, src/apps/applets/tests/unit/test_filter_schedule_events.py, src/config/applet.py
🔗 [Jira Ticket M2-5602](https://mindlogger.atlassian.net/browse/M2-5602)
- Added cli command to generate daily user flow schedule.
Example usage:
```bash
python src/cli.py applet-ema generate-user-flow-schedule 2024-03-06
```
=> M2-5602: Add command to export daily user flow schedule

src/apps/applets/commands/applet_ema.py, src/config/applet.py, src/infrastructure/utility/cdn_client.py
🔗 [Jira Ticket M2-5667](https://mindlogger.atlassian.net/browse/M2-5667)
- Append flow events data to previously generated file if one exists
- Change flow events generation command:
```
python src/cli.py applet-ema export-flow-schedule
```
=> M2-5599 M2-5667 Append export content to existing file

src/apps/workspaces/crud/user_applet_access.py, src/apps/workspaces/tests/test_workspaces.py
resolves: M2-5611
Objective
Fix email for shell account in respondent list
=> M2-5611: Case for shell account emails

src/apps/applets/commands/applet_ema.py, src/apps/applets/tests/unit/test_filter_schedule_events.py
🔗 [Jira Ticket M2-5697](https://mindlogger.atlassian.net/browse/M2-5697)
- Removed 'ALWAYS' events
- Added filter by start_date
=> M2-5697: Add filter by start_date, removed 'ALWAYS' events

src/apps/applets/commands/applet_ema.py, src/apps/job/errors.py, src/apps/job/service.py, src/config/applet.py
🔗 [Jira Ticket M2-5675](https://mindlogger.atlassian.net/browse/M2-5675)
- Change ema applet export config
- Prevent multiple execution of the same command
=> M2 5675 execution check

src/apps/applets/commands/__init__.py, src/apps/applets/commands/applet_ema.py, src/apps/applets/tests/unit/test_filter_schedule_events.py, src/apps/job/errors.py, src/apps/job/service.py, src/cli.py, src/config/__init__.py, src/config/applet.py, src/infrastructure/dependency/cdn.py, src/infrastructure/utility/cdn_client.py
🔗 [Jira Ticket M2-5599](https://mindlogger.atlassian.net/browse/M2-5599)
Create cli command to generate activity flow csv file for dedicated applet and upload to S3 operations bucket
s3 path: operations/mindlogger/export-ema/{applet_id}/flow-items.csv
Required env vars:
```
APPLET_EMA__ID
APPLET_EMA__NAME
```
Commands:
- Generate flow items data and upload to s3
```
python src/cli.py applet-ema export-flows
```
- Generate flow events data and upload to s3
```
python src/cli.py applet-ema export-flow-schedule
```
=> M2-5599 Create cli commands to generate ema export csv files

src/apps/mailing/static/templates/footers/footer_info_en.html, src/apps/mailing/static/templates/header.html, src/apps/mailing/static/templates/reset_password_en.html, src/apps/mailing/static/templates/response_alert_en.html, src/apps/mailing/static/templates/transfer_ownership_registered_user_en.html, src/apps/mailing/static/templates/transfer_ownership_unregistered_user_en.html
🔗 [Jira Ticket M2-5346](https://mindlogger.atlassian.net/browse/M2-5346)
- CSS and text changes on email templates [Figma reference](https://www.figma.com/file/hHPm6VvnfEyEcKvcVsg4UO/Transactional-emails?type=design&node-id=424-41&mode=design&t=6WFQKPM4LARkIVXw-0)
**Old**:
**New**:
=> M2-5346: email copy, identation and styles.

src/infrastructure/utility/notification_client.py
🔗 [Jira Ticket M2-5733](https://mindlogger.atlassian.net/browse/M2-5733)
- Change firebase notification config as requested by @vmkhitaryanscn 
Needs to be tested with mobile app on iOS after deployment to dev or test environment.
=> M2-5733: firebase notification priority for ios

src/apps/alerts/crud/alert.py, src/apps/alerts/service.py, src/apps/alerts/test_alerts.py
(https://mindlogger.atlassian.net/jira/servicedesk/projects/MLA/knowledge/articles/340623543?spaceKey=MLA)
🔗 [Jira Ticket M2-5568](https://mindlogger.atlassian.net/browse/M2-5568)
- [Alerts secretId getting from subject instead of role]
Autotests
=> Fix secret id for alerts

Pipfile, src/apps/activities/commands/reindex_items.py, src/apps/answers/commands/convert_assessments.py, src/apps/applets/commands/applet_ema.py, src/apps/schedule/commands/remove_events.py, src/apps/shared/commands/__init__.py, src/apps/shared/commands/encryption.py, src/apps/shared/commands/patch_commands.py, src/apps/users/commands/token.py, src/apps/workspaces/commands/arbitrary_server.py, src/cli.py, src/infrastructure/commands/utils.py
🔗 [Jira Ticket M2-5874](https://mindlogger.atlassian.net/browse/M2-5874)
- New commands:
```
python src/cli.py encryption encrypt <data>
python src/cli.py encryption decrypt <encrypted-data>
```
- Ability to run commands with pipenv
```
pipenv run cli <command>
```
=> M2-5874 Implement commands to encrypt/decrypt data in DB

src/apps/file/api/file.py, src/apps/file/domain.py, src/apps/file/test_file.py
🔗 [Jira Ticket M2-5598](https://mindlogger.atlassian.net/browse/M2-5598)
- Added optional targetExtension to the body of the request to generate the upload presigned post urls for `webm` files which should be converted to the `mp4` format
=> M2-5598: Add support for webm->mp4

src/apps/answers/domain/answers.py, src/apps/answers/service.py
🔗 [Jira Ticket M2-5896](https://mindlogger.atlassian.net/browse/M2-5896)
- Add end_datetime to domain models
- Add end_datetime to response model
=> M2-5896 Add end_datetime for answers in review

.env.default, src/apps/shared/encryption.py, src/config/authentication.py, src/config/secret.py
🔗 [Jira Ticket M2-4388](https://mindlogger.atlassian.net/browse/M2-4388) (Only remove keys from config)
- Removed auth credentials from config settings
- Removed secret key from secret. Added secret key for local development to the .env.default
=> M2-4388: Add checking if secret_key and auth keys are set

src/config/__init__.py, src/config/authentication.py
🔗 [Jira Ticket M2-5955](https://mindlogger.atlassian.net/browse/M2-5955)
Fix the error with authentication settings validation when all required values are set in .env file. Prevent initialization without env vars
=> M2-5955 Fix authentication config

src/infrastructure/utility/cdn_client.py
🔗 [Jira Ticket M2-5807](https://mindlogger.atlassian.net/browse/M2-5807)
- [Added proper exception and http code for situation when key not exist]
=> M2-5807 Fixed problem with 500 error when key not exist

src/apps/answers/domain/answers.py
🔗 [Jira Ticket M2-6024](https://mindlogger.atlassian.net/browse/M2-6024)
=> M2-6024 Fix answer.client model validation

src/apps/answers/crud/answers.py, src/apps/answers/domain/answers.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py
🔗 [Jira Ticket M2-#](https://mindlogger.atlassian.net/browse/M2-5553)
- `createdAt` for reviewer assessment reviews list
- `lastAnswerDate` for summary activity list
- `lastActivityDate` for review activity list
<!--
Replace this with a series of test steps & expected outcomes.
=> M2-5553: Add time attribute to reviews, activity list and answers

src/apps/invitations/api.py, src/apps/invitations/crud.py, src/apps/invitations/db/schemas.py, src/apps/invitations/domain.py, src/apps/invitations/router.py, src/apps/invitations/services.py, src/apps/invitations/test_invite.py, src/apps/shared/domain/base.py, src/apps/shared/domain/custom_validations.py, src/apps/subjects/api.py, src/apps/subjects/crud/subject.py, src/apps/subjects/domain.py, src/apps/subjects/errors.py, src/apps/subjects/router.py, src/apps/subjects/services/subjects.py, src/apps/transfer_ownership/service.py, src/apps/workspaces/api.py, src/apps/workspaces/tests/test_workspaces.py, src/infrastructure/database/migrations/versions/2024_02_08_18_28-add_subjects.py
🔗 [Jira Ticket M2-5925](https://mindlogger.atlassian.net/browse/M2-5925)
🔗 [Jira Ticket M2-5738](https://mindlogger.atlassian.net/browse/M2-5738)
🔗 [Jira Ticket M2-6059](https://mindlogger.atlassian.net/browse/M2-6059)
=> M2-5925 M2-5738 M2-6059 Remove invitations on shell account deletion, Fix invitation creation issues

src/apps/answers/crud/answers.py, src/apps/answers/domain/answers.py, src/apps/answers/service.py
🔗 [Jira Ticket](https://mindlogger.atlassian.net/browse/M2-5960)
- Additional data for EP `answers/applet/{appletId}/answers/{answerId}/activities/{activityId}`
=> M2-5960: add createdAt, identifiers, version for activity answer ep

src/apps/workspaces/commands/arbitrary_server.py, src/apps/workspaces/service/workspace.py
🔗 [Jira Ticket M2-6046](https://mindlogger.atlassian.net/browse/M2-6046)
- Add command to remove arbitrary settings for workspace by owner-id
=> M2-6064: Add command to remove arbitrary settings for workspace

src/apps/workspaces/commands/arbitrary_server.py, src/apps/workspaces/domain/workspace.py
🔗 [Jira Ticket M2-6047](https://mindlogger.atlassian.net/browse/M2-6047)
- Add alembic_version and owner_id to the console output
=> M2-6047: Add user_id and alembic version to the console output

src/apps/workspaces/commands/arbitrary_server.py, src/apps/workspaces/domain/workspace.py
🔗 [Jira Ticket M2-5480](https://mindlogger.atlassian.net/browse/M2-5480)
- Replace owner-id with owner-email for arbitrary cli arguemts
=> M2-5480: Replace owner-id with owner-email for arbitrary cli arguemts

src/apps/answers/api.py, src/apps/answers/crud/answer_items.py, src/apps/answers/domain/answers.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py
🔗 [Jira Ticket](https://mindlogger.atlassian.net/browse/M2-5562)
`/answers/applet/${applet_id}/activities/${activity_id}/answers.`
- Review counters for endpoint added
=> M2-5562: Add reviews counter

src/apps/file/api/file.py
🔗 [Jira Ticket M2-5807](https://mindlogger.atlassian.net/browse/M2-5807)
- [Fixed error when downloading file]
=> M2-5807 Fixed error when downloading file

src/apps/answers/crud/answers.py, src/apps/answers/domain/answers.py, src/apps/answers/service.py
🔗 [Jira Ticket](https://mindlogger.atlassian.net/browse/M2-5960)
=> M2-5960: Change filter for identifier and identifier datatype

src/apps/answers/service.py
🔗 [Jira Ticket M2-5969](https://mindlogger.atlassian.net/browse/M2-5960)
=> M2-5960: Use version for getting datetime to avoid date mismatch

src/apps/file/api/file.py
🔗 [Jira Ticket M2-5807](https://mindlogger.atlassian.net/browse/M2-5807)
- [Fixed error when downloading file with answers]
=> M2-5807 Fixed error when downloading file with answers

src/apps/answers/service.py, src/apps/answers/tests/test_answers.py
=> M2-6273: Fix "has_answer" flag (#1232)

src/apps/activities/db/schemas/activity.py, src/apps/activity_flows/crud/flow_history.py, src/apps/activity_flows/db/schemas/flow.py, src/apps/activity_flows/db/schemas/flow_item.py, src/apps/activity_flows/domain/flow_full.py, src/apps/answers/api.py, src/apps/answers/crud/answers.py, src/apps/answers/db/schemas.py, src/apps/answers/domain/answer_items.py, src/apps/answers/domain/answers.py, src/apps/answers/router.py, src/apps/answers/service.py, src/apps/answers/tests/conftest.py, src/apps/answers/tests/test_answers.py, src/apps/applets/db/schemas/applet.py, src/apps/applets/tests/unit/test_history_mixin.py, src/apps/shared/filtering.py, src/infrastructure/database/base.py, src/infrastructure/database/mixins.py, src/infrastructure/lifespan.py
🔗 [Jira Ticket M2-6204](https://mindlogger.atlassian.net/browse/M2-6204)
- Endpoint to get flow submission data: `GET /answers/applet/{applet_id}/flows/{flow_id}/submissions/{submit_id}`
=> M2-6204 Implement flow submission endpoint

src/apps/activities/crud/activity_history.py, src/apps/activity_flows/crud/flow_history.py, src/apps/answers/api.py, src/apps/answers/crud/answers.py, src/apps/answers/domain/answers.py, src/apps/answers/router.py, src/apps/answers/service.py, src/apps/answers/tests/conftest.py, src/apps/answers/tests/test_answers.py, src/apps/workspaces/service/check_access.py
🔗 [Jira Ticket M2-6258](https://mindlogger.atlassian.net/browse/M2-6258)
- EP for summary flow list `/answers/applet/{applet_id}/summary/flows`
=> M2-6258: Activity flow list for summary

src/apps/activities/crud/activity_history.py, src/apps/activities/services/activity_item_history.py, src/apps/answers/api.py, src/apps/answers/crud/answers.py, src/apps/answers/domain/answers.py, src/apps/answers/router.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py, src/apps/answers/tests/test_answers_arbitrary.py
🔗 [Jira Ticket M2-6257](https://mindlogger.atlassian.net/browse/M2-6257)
- Update /answers/applet/{applet_id}/activities/{activity_id}/answers/{answer_id} format
=> M2-6257 Update activity answers format

src/apps/answers/crud/answers.py, src/apps/answers/domain/answers.py, src/apps/answers/tests/test_answers.py
🔗 [Jira Ticket M2-6257](https://mindlogger.atlassian.net/browse/M2-6257)
- Change summary format for endpoints:
```
GET /answers/applet/{applet_id}/activities/{activity_id}/answers/{answer_id}
GET /applet/{applet_id}/flows/{flow_id}/submissions/{submit_id}
```
Previous version:
```
{
"endDatetime": "<datetime>",
"createdAt": "<datetime>",
"identifier": "<encrypted>",
"version": "<version>"
}
```
New version:
```
{
"endDatetime": "<datetime>",
"createdAt": "<datetime>",
"identifier": {
"identifier": "<encrypted>",
"userPublicKey": "<key>",
"lastAnswerDate": "<datetime>"
},
"version": "<version>"
}
```
=> M2-6257 Update activity answers / flow answers summary format

src/apps/activities/crud/activity.py, src/apps/activities/crud/activity_history.py, src/apps/activities/services/activity_history.py, src/apps/answers/crud/answer_items.py, src/apps/answers/crud/answers.py, src/apps/answers/db/schemas.py, src/apps/answers/domain/answers.py, src/apps/answers/service.py, src/infrastructure/database/base.py
🔗 [Jira Ticket M2-6364](https://mindlogger.atlassian.net/browse/M2-6364)
- Fix answers activities dates
- Rework answers activities endpoint `GET /answers/applet/{applet_id}/review/activities?respondentId={respondent_id}&createdDate={date}`
=> M2-6364 Fix response activities date, rework endpoint

src/apps/answers/api.py, src/apps/answers/crud/answers.py, src/apps/answers/domain/answers.py, src/apps/answers/filters.py, src/apps/answers/router.py, src/apps/answers/service.py, src/apps/answers/tests/conftest.py, src/apps/answers/tests/test_answers.py
🔗 [Jira Ticket M2-6384](https://mindlogger.atlassian.net/browse/M2-6384)
- Implement flow list endpoint for responses review tab
`GET /answers/applet/{applet_id}/review/flows`
=> M2-6384 Implement answers flow list endpoint

src/apps/activity_flows/crud/flow_history.py, src/apps/activity_flows/service/flow.py, src/apps/answers/api.py, src/apps/answers/crud/answer_items.py, src/apps/answers/crud/answers.py, src/apps/answers/db/schemas.py, src/apps/answers/domain/answers.py, src/apps/answers/filters.py, src/apps/answers/router.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py, src/apps/applets/api/applets.py, src/apps/applets/domain/applet_history.py, src/apps/shared/domain/custom_validations.py
🔗 [Jira Ticket M2-5559](https://mindlogger.atlassian.net/browse/M2-5559)
- Flow identifiers endpoint
`GET /answers/applet/{applet_id}/flows/{flow_id}/identifiers`
- Flow versions endpoint
`GET /answers/applet/{applet_id}/flows/{flow_id}/versions`
- Flow submissions endpoint
`GET /answers/applet/{applet_id}/flows/{flow_id}/submissions`
=> M2-5559 Implement flow endpoints for summary tab

src/apps/file/api/file.py, src/apps/file/storage.py, src/apps/users/tests/test_reencrypt_user_answers.py, src/apps/workspaces/commands/arbitrary_server.py, src/apps/workspaces/domain/workspace.py, src/apps/workspaces/service/workspace.py, src/apps/workspaces/tests/unit/domain/test_workspace_arbitrary.py, src/infrastructure/dependency/cdn.py
- Add arbitrary ping command to make sure that after setup arbitrary settings everything works
- REQUIRED. Please ask somebody from DevOps team AWS credentials for arbitrary bucket and arbitrary bucket name.
- Database can be created locally. For example `create database arbitrary` in psql or another database tool.
- Add arbitrary settings for some user: `python src/cli.py arbitrary add --db-uri {db-uri} --storage-type aws --storage-secret-key {secret-key} --storage-access-key {access-key} --storage-region us-east-1 --storage-bucket {bucket-name}  {user email}`. Or using docker: `docker compose run app python src/cli.py arbitrary add --db-uri {db-uri} --storage-type aws --storage-secret-key {secret-key} …
=> M2-6228: Add ping command for arbitrary

src/apps/invitations/api.py, src/apps/invitations/domain.py, src/apps/invitations/test_invite.py
Add language support to subject ⇒ full account invitation endpoint
🔗 [Jira Ticket M2-6283](https://mindlogger.atlassian.net/browse/M2-6283)
=> M2 6283 be add language support to subject full account invitation endpoint

Makefile, compose/fastapi/Dockerfile, compose/fastapi/Dockerfile.app, compose/fastapi/migrate, compose/fastapi/start
🔗 [Jira Ticket M2-6336](https://mindlogger.atlassian.net/browse/M2-6336)
- Move alembic migrations to the separate process for DevOps purposes.
=> M2-6336: Move migrations to the separate command

src/apps/shared/commands/patch_commands.py, src/apps/shared/commands/patches/m2_5551_delete_invitations_of_existing_respondent.sql
🔗 [Jira Ticket M2-5551](https://mindlogger.atlassian.net/browse/M2-5551)
- Patch to delete wrong pending invitations
=> M2-5551 Create patch to delete pending invitations of existing respondent

src/apps/answers/crud/answers.py, src/apps/answers/service.py, src/apps/invitations/api.py, src/apps/invitations/errors.py, src/apps/invitations/services.py, src/apps/subjects/errors.py, src/apps/workspaces/service/user_applet_access.py
🔗 [Jira Ticket M2-6165](https://mindlogger.atlassian.net/browse/M2-6165)
- Remove user_id from soft-deleted subject on conflict with invited one (unique constraint [applet_id, user_id])
- Move answers from deleted subject to invited one
Tests are going to be impelented under 🔗 [Jira Ticket M2-6541](https://mindlogger.atlassian.net/browse/M2-6541) after merging answers tests from develop
=> M2-6165 Merge subjects on invitation acceptance conflict

src/apps/activities/domain/conditions.py, src/apps/activities/domain/response_values.py, src/apps/activities/tests/unit/domain/test_activity_item_create.py, src/apps/activities/tests/unit/domain/test_custom_validation.py
🔗 [Jira Ticket M2-6276](https://mindlogger.atlassian.net/browse/M2-6276)
- score value type for SingleSelect, MultiSelect, Slider items is changed to float
- value type for condition in Score and Sections is changed to float
Need to check report server for compatibility
=> fix: change score value type to float(M2-6276)

.github/workflows/oasdif.yaml, src/apps/invitations/domain.py, src/apps/invitations/services.py, src/apps/invitations/test_invite.py, src/apps/shared/commands/patch_commands.py, src/apps/shared/commands/patches/m2_6504_update_subject_tags.sql, src/apps/subjects/constants.py, src/apps/workspaces/service/user_applet_access.py, src/apps/workspaces/tests/test_workspaces.py
🔗 [Jira Ticket M2-6504](https://mindlogger.atlassian.net/browse/M2-6504)
=>  Add subject tag as 'Team' to managers/reviewers (M2-6504)

src/apps/shared/commands/patch_commands.py, src/apps/shared/commands/patches/m2_6057_drawing_proportion.py
🔗 [Jira Ticket M2-6057](https://mindlogger.atlassian.net/browse/M2-6057)
Patch for enabling proportion in drawing item
Need to run the following to run the patch:
`python src/cli.py patch exec M2-6057   `
=> feat: patch for enabling proportion in drawing item (M2-6057)

src/apps/applets/commands/applet_ema.py
🔗 [Jira Ticket M2-5698](https://mindlogger.atlassian.net/browse/M2-5698)
Update ema commands according to shell-account changes
=> feat(shell-account): Update ema commands with correct source tables of respondent info (M2-5698)

.github/workflows/drop_db.yaml
Pipeline is needed to remove the database after removing the associated infrastructure to test open PR.
🔗 [Jira Ticket M2-6540](https://mindlogger.atlassian.net/browse/M2-6540)
- Pipeline for database deletion
=> chore: Add pipeline for delete temp database (M2-6540)

src/apps/applets/service/applet.py, src/apps/applets/tests/test_applet_link.py
🔗 [Jira Ticket M2-6623](https://mindlogger.atlassian.net/browse/M2-6623)
🔗 [Jira Ticket M2-6670](https://mindlogger.atlassian.net/browse/M2-6670)
- Fix access link creation
- Add email to guest subject
=> fix(shell-account): Fix access link creation after deletion(M2-6623, M2-6670)

src/apps/answers/api.py, src/apps/answers/crud/answers.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py, src/apps/workspaces/crud/user_applet_access.py, src/apps/workspaces/service/check_access.py
🔗 [Jira Ticket M2-6688](https://mindlogger.atlassian.net/browse/M2-6688)
- Fix permission check
=> fix(shell-account): Fix permissions check for summary EPs(M2-6688)

Pipfile, Pipfile.lock, src/apps/activities/domain/activity_base.py, src/apps/activities/domain/activity_item_base.py, src/apps/activities/domain/scores_reports.py, src/apps/activities/tests/unit/domain/test_activity_item_create.py, src/apps/activities/tests/unit/domain/test_scores_reports.py, src/apps/activity_flows/domain/base.py, src/apps/applets/domain/base.py, src/apps/applets/tests/test_applet.py, src/apps/applets/tests/test_applet_activity_items.py, src/apps/shared/domain/custom_validations.py, src/apps/shared/test/unit/test_shared_custom_validation.py
🔗 [Jira Ticket M2-5699](https://mindlogger.atlassian.net/browse/M2-5699)
Sanitization for these fields are added:
- Applet: display_name, about, description, report_email_body
- Activity: name, description
- ActivityFlow: name, description
- Activity Item: question, score message, section message, score conditional logic message
=> bugfix: Sanitize fields to prevent script injection (M2-5699)

src/apps/activities/domain/custom_validation_subscale.py, src/apps/activities/tests/unit/domain/test_custom_validation_subscale.py
🔗 [Jira Ticket M2-6275](https://mindlogger.atlassian.net/browse/M2-6275)
- Allow negative raw score value in subscales
=> bugfix: Allow negative raw score value (M2-6275)

src/apps/alerts/ws_api.py, src/apps/answers/service.py
Read and return subject info to alert
🔗 [Jira Ticket M2-6613](https://mindlogger.atlassian.net/browse/M2-6613)
- Added information about subject into ws alert
=> fix: M-6613 Subject info missing in alert

src/apps/answers/tests/conftest.py, src/apps/answers/tests/test_answers.py
🔗 [Jira Ticket M2-6617](https://mindlogger.atlassian.net/browse/M2-6617)
=> fix:  Fix closed session in answer tests (M2-6617)

.github/workflows/run_build.yaml, .github/workflows/run_deploy_dev.yaml, .github/workflows/run_deploy_test.yaml, .github/workflows/run_deploy_uat.yaml
Deployment to UAT and Test environments
https://mindlogger.atlassian.net/browse/M2-6595
=> M2 6595 configure deploy to test/uat

.github/workflows/run_deploy_dev.yaml
=> Refactored deployment conditions

.gitignore, Makefile, src/apps/answers/api.py, src/apps/answers/domain/answers.py, src/apps/answers/errors.py, src/apps/answers/filters.py, src/apps/answers/router.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py, src/apps/shared/exception.py, src/apps/test_data/domain.py
Add new endpoint to validate all parameters for takenow flow before submit an assessment
PS: Fixed an error on tests, it was failing when in UTC date now is near midnight and some timedelta "jump" no next day
🔗 [Jira Ticket M2-6381](https://mindlogger.atlassian.net/browse/M2-6381)
=> feature: Add new endpoint to validate takenow parameters (M2-6381)

.github/workflows/run_deploy_dev.yaml
=> addded new condition

src/apps/applets/tests/test_applet_activity_items.py, src/apps/schedule/domain/schedule/requests.py, src/apps/schedule/tests/unit/domain/test_schedule_request_data.py
🔗 [Jira Ticket M2-6741](https://mindlogger.atlassian.net/browse/M2-6741)
- Notification and reminder are allowed on cross-day event
=> bugfix: Notification and reminder on cross-day events (M2-6741)

.github/workflows/run_deploy_dev.yaml
=> added new condition

.github/workflows/run_deploy_dev.yaml
=> added permissions

.github/workflows/run_deploy_dev.yaml
Fixing ECS Service update logic
=> changed workflow

.github/workflows/run_deploy_dev.yaml
=> fix for dev  deployemnt workflow

.github/workflows/run_deploy_dev.yaml
=> update services fix

.github/workflows/run_deploy_dev.yaml
condition is refactored
- [Thing]
=> condition is refactored

.github/workflows/run_build.yaml, .github/workflows/run_deploy_dev.yaml
changed to workflow_call
- [Thing]
=> changed to workflow_call

.github/workflows/run_build.yaml, .github/workflows/run_deploy_test.yaml, .github/workflows/run_deploy_uat.yaml
changed other deployment steps
- [Thing]
=> changed call-workflow

.github/workflows/run_build.yaml
=> changed PR condition

.github/workflows/run_build.yaml
=> added dependency for build job

.github/workflows/run_deploy_dev.yaml, .github/workflows/run_deploy_test.yaml, .github/workflows/run_deploy_uat.yaml
=> added pull_request dependecy and inputs to called jobs

.github/workflows/run_build.yaml, .github/workflows/run_deploy_dev.yaml, .github/workflows/run_deploy_test.yaml, .github/workflows/run_deploy_uat.yaml
added condition for tags
- [Thing]
=> testing deployment

.github/workflows/run_deploy_staging.yaml, .github/workflows/run_deploy_test.yaml
added regex for a release branch
- [Thing]
=> added stage for deployment to stage

.github/workflows/run_deploy_dev.yaml, .github/workflows/run_deploy_staging.yaml, .github/workflows/run_deploy_test.yaml, .github/workflows/run_deploy_uat.yaml
Added possibility to send Slack notifications after deploy is completed
https://mindlogger.atlassian.net/browse/M2-6597
=> added slack notifications feature

.github/workflows/run_deploy_dev.yaml, .github/workflows/run_deploy_staging.yaml, .github/workflows/run_deploy_test.yaml, .github/workflows/run_deploy_uat.yaml
=> changed slack token param

.github/workflows/run_deploy_dev.yaml, .github/workflows/run_deploy_staging.yaml, .github/workflows/run_deploy_test.yaml, .github/workflows/run_deploy_uat.yaml
=> fixed secrets definition

.github/workflows/run_deploy_staging.yaml, .github/workflows/run_deploy_test.yaml, .github/workflows/run_deploy_uat.yaml
=> changed env secrets

src/apps/applets/tests/test_applet_activity_items.py, src/apps/schedule/domain/schedule/requests.py, src/apps/schedule/tests/unit/domain/test_schedule_request_data.py
bugfix: Notification and reminder on cross-day events (M2-6741) (#1329)
=> Merge release to develop

src/apps/activities/errors.py, src/apps/activity_flows/crud/flow_history.py, src/apps/answers/api.py, src/apps/answers/crud/answers.py, src/apps/answers/router.py, src/apps/answers/service.py, src/apps/answers/tests/conftest.py, src/apps/answers/tests/test_answers.py
…lows
🔗 [Jira TicketM2-5692](https://mindlogger.atlassian.net/browse/M2-5692)
- New endpoint for flow's last report
=> feature(flow's latest report): Latest report support for flow (M2-5692)

src/apps/shared/commands/patch_commands.py, src/apps/shared/commands/patches/m2_6879_create_deleted_respondents.py
…ondent's roles
🔗 [Jira Ticket M2-6879](https://mindlogger.atlassian.net/browse/M2-6879)
- Patch for create deleted respondent role
=> fix(shell-account): Patch for creation of not migrated deleted respondent roles (M2-6879)

src/apps/answers/tests/test_answers.py, src/apps/shared/commands/patch_commands.py, src/apps/shared/commands/patches/m2_6504_update_subject_tags.sql
Hot fix for multiinformant patch
=> fix: Multiinformant patch to consider applet context in query

.github/workflows/run_deploy_prod.yaml
Testing approvals for deployment based on a dev environment
=> added condition to dev for testing

.github/workflows/run_deploy_dev.yaml
=> removed testing condition

src/apps/answers/service.py, src/apps/answers/tests/test_answers.py
🔗 [Jira Ticket M2-6920](https://mindlogger.atlassian.net/browse/M2-6920)
- IsComplited attribute fixed for submission details endpoint
=> bugfix(summary-flows) Calc isCompleted field for submission details (M2-6920)

src/apps/answers/crud/answers.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py
🔗 [Jira Ticket M2-6921](https://mindlogger.atlassian.net/browse/M2-6921)
🔗 [Jira Ticket M2-6238](https://mindlogger.atlassian.net/browse/M2-6238)
- Summary flow list item's attribute 'hasAnswer = True' only for completed submissions
- Flows order fixed
=> bugfix(summary-flows) Filter out not completed submissions and use flows order (M2-6921, M2-6238)

src/apps/answers/api.py, src/apps/answers/domain/answers.py, src/apps/answers/router.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py, src/apps/applets/tests/fixtures/applets.py, src/apps/subjects/crud/subject.py, src/apps/workspaces/crud/user_applet_access.py, src/apps/workspaces/service/workspace.py
Add new endpoint retuning applet submissions and stats ( number of submissions and participants)
🔗 [Jira Ticket M2-6575](https://mindlogger.atlassian.net/browse/M2-6575)
🔗 [Jira Ticket M2-6574](https://mindlogger.atlassian.net/browse/M2-6574)
=> feature: Add new endpoint retuning applet submissions and stats (M2-6575,M2-6574)

src/apps/answers/crud/notes.py, src/apps/answers/domain/answers.py, src/apps/answers/tests/test_answers.py
🔗 [Jira Ticket M2-5654](https://mindlogger.atlassian.net/browse/M2-5654)
=> Fix user id added to notes list (M2-5654)

src/apps/shared/commands/patch_commands.py, src/apps/shared/commands/patches/m2_6968_create_flows_old_versions.py
🔗 [Jira Ticket M2-6968](https://mindlogger.atlassian.net/browse/M2-6968)
- Create patch for flow history creation for particular 2 applets
```
python src/cli.py patch exec M2-6968
```
=> feat: patch to create flows for particular applets (M2-6968)

src/infrastructure/database/migrations_arbitrary/env.py
🔗 [Jira Ticket M2-7024](https://mindlogger.atlassian.net/browse/M2-7024)
=> fix(migration): Properly handle not responding connections (M2-7024)

src/apps/answers/service.py, src/apps/integrations/loris/domain.py, src/apps/integrations/loris/service/loris.py, src/apps/integrations/loris/tests/test_domain.py, src/config/integrations.py
🔗 [Jira Ticket M2-6646](https://mindlogger.atlassian.net/browse/M2-6646)
- Sending missing versions of the applet to loris
- Sending missing answers to loris
=> feat(Loris): Send to loris versions of applets & all answers (M2-6646)

src/apps/transfer_ownership/tests.py, src/apps/workspaces/api.py, src/apps/workspaces/crud/user_applet_access.py, src/apps/workspaces/domain/workspace.py, src/apps/workspaces/tests/test_workspaces.py
Add pending invitations to workspace managers list
- Returning new fields titles and status (pending or approved)
- Do not break api, keep it working current FE
🔗 [Jira Ticket M2-6753](https://mindlogger.atlassian.net/browse/M2-6753)
=> feature: Add pending invitations to workspace managers list (M2-6753)

src/apps/shared/commands/patches/m2_6879_create_deleted_respondents.py
🔗 [Jira Ticket M2-7055](https://mindlogger.atlassian.net/browse/M2-7055)
=> fix(patch): fix duplication error in patch "M2-6879" for arbitrary DBs (M2-7055)

src/apps/answers/crud/answer_items.py, src/apps/answers/tests/conftest.py, src/apps/answers/tests/test_answers.py
🔗 [Jira Ticket M2-7053](https://mindlogger.atlassian.net/browse/M2-7053)
=> fix(responses): Fix for emptyIdentifiers filter (M2-7053)

.github/workflows/run_deploy_dev.yaml
=> added required parameter

.github/workflows/destroy-preview-env.yaml, .github/workflows/pr-open.yml, .github/workflows/run_build.yaml, .github/workflows/run_deploy_dev.yaml, .github/workflows/tests.yaml, copilot/scripts/cleanup.sh, copilot/scripts/env-stop.sh, src/apps/activity_flows/crud/flow_history.py, src/apps/activity_flows/domain/flow_full.py, src/apps/answers/service.py, src/apps/answers/tests/conftest.py, src/apps/answers/tests/test_answer_for_cases.py, src/apps/answers/tests/test_answers.py, src/apps/workspaces/commands/arbitrary_server.py, src/apps/workspaces/domain/workspace.py, src/apps/workspaces/service/workspace.py
Syncing feature/multiinformant-metapod with develop branch
🔗 [Jira Ticket M2-7017](https://mindlogger.atlassian.net/browse/M2-7017)
`pipenv sync --system --dev`
`alembic upgrade head`
=> M2-7017: Merge backend develop branch sprint 11 wk 2

.github/workflows/run_build.yaml, .github/workflows/run_deploy_dev.yaml
=> refactore pull_request condition

.github/workflows/run_build.yaml
=> changed link to reusable workflow

.github/workflows/run_build.yaml
=> M2 6599 run migrations

.github/workflows/run_deploy_dev.yaml
=> debug IMAGE_NAME variable

.github/workflows/run_deploy_dev.yaml
=> added another step for migration deployment

.github/workflows/run_deploy_dev.yaml
=> changed entrypoint

src/apps/activity_flows/crud/flow_history.py, src/apps/activity_flows/service/flow.py, src/apps/answers/api.py, src/apps/answers/crud/answers.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py, src/apps/applets/api/applets.py
🔗 [Jira Ticket M2-7030](https://mindlogger.atlassian.net/browse/M2-7030)
- Add a flow to the applet
- Pass activities in the flow using web\mobile
- Delete the flow from the the applet
- Go to the summary tab
- Check the network tab for endpoints, identifiers, versions, and submissions to ensure there are no errors.
=> fix(summary): Fix getting versions, identifiers, submissions for deleted flows (m2-7030)

src/apps/integrations/loris/api/applets.py, src/apps/integrations/loris/domain.py, src/apps/integrations/loris/router.py, src/apps/integrations/loris/service/loris.py, src/apps/integrations/loris/tests/test_api_applet.py, src/apps/integrations/loris/tests/test_routes.py, src/config/integrations.py
Added support for Multiple Visits
🔗 [Jira Ticket M2-6649](https://mindlogger.atlassian.net/browse/M2-6649)
=> feat: Multiple Visits (M2-6649)

src/apps/integrations/loris/domain.py
Added detailed information into domain models
🔗 [Jira Ticket M2-6649](https://mindlogger.atlassian.net/browse/M2-6649)
=> fix: Multiple Visits (detailed information into domain models) (M2-6649) 

src/apps/integrations/loris/domain.py, src/apps/integrations/loris/tests/test_api_applet.py, src/apps/integrations/loris/tests/test_routes.py
Added detailed information into domain models, fixed tests
🔗 [Jira Ticket M2-6649](https://mindlogger.atlassian.net/browse/M2-6649)
=> fix: Multiple Visits (fix tests, fix models) (M2-6649)

src/apps/workspaces/crud/user_applet_access.py
Filters are not properly applied on workspace managers list
🔗 [Jira Ticket M2-7196](https://mindlogger.atlassian.net/browse/M2-7196)
=> fix: Not applying filters properly in workspace managers list (M2-7196)

src/apps/integrations/loris/domain.py, src/apps/integrations/loris/service/loris.py, src/infrastructure/database/migrations/versions/2024_07_04_17_14-actualize_loris_with_dev_branch.py, src/infrastructure/database/migrations_arbitrary/versions/2024_07_04_17_20-actualize_loris_with_dev_branch.py
🔗 [Jira Ticket M2-7238](https://mindlogger.atlassian.net/browse/M2-7238)
=> fix: Responses cannot be uploaded by the same user to more than one applet (M2-7238)

src/apps/shared/commands/patch_commands.py
We have a duplicate code in merging develop branch in main branch, so this PR is to remove it
NO-TICKET
=> Fix: Removed duplicate code in merge

src/apps/activities/domain/response_type_config.py, src/apps/activities/services/activity_item_change.py, src/apps/activities/tests/fixtures/configs.py, src/apps/activities/tests/test_activities.py
🔗 [Jira Ticket M2-7229](https://mindlogger.atlassian.net/browse/M2-7229)
- New "portrait_layout" flag for single/multiple selection item types
=> feat: Add portrait_layout property to single/multi selection config (M2-7229)

src/apps/answers/crud/answers.py, src/apps/answers/service.py, src/apps/answers/tests/conftest.py, src/apps/answers/tests/test_answers.py
🔗 [Jira Ticket M2-7290](https://mindlogger.atlassian.net/browse/M2-7290)
- Update submit_id validation allowing sending answer for latest activity ignoring activity order in the flow
=> chore: Update submit_id validation allowing flow autocomletion (M2-7290)

src/apps/shared/subjects.py, src/apps/subjects/api.py, src/apps/subjects/tests/tests.py
🔗 [Jira Ticket M2-7414](https://mindlogger.atlassian.net/browse/M2-7414)
This PR fixes the broken unit tests from #1494, and adds some tests that were missing from that PR.
Nothing to do manually. Just pay attention to the result of the checks on the PR. They should all be successful
N/A
=> fix: Failing unit tests (M2-7414)

src/apps/answers/domain/answers.py
🔗 [Jira Ticket M2-7416](https://mindlogger.atlassian.net/browse/M2-7416)
=> fix: Make answers.consent_to_share optional on answer create EP (M2-7416)

src/apps/activities/domain/activity_create.py, src/apps/activities/domain/activity_update.py, src/apps/activities/domain/custom_validation.py, src/apps/activities/domain/response_type_config.py, src/apps/activities/domain/response_values.py, src/apps/activities/errors.py, src/apps/activities/tests/fixtures/configs.py, src/apps/activities/tests/fixtures/items.py, src/apps/activities/tests/fixtures/response_values.py, src/apps/applets/tests/test_applet_activity_items.py
Add new Phrasal template activity item
🔗 [Jira Ticket M2-7168](https://mindlogger.atlassian.net/browse/M2-7168)
=> feature: Add new Phrasal Template activity item type ( M2-7168)

src/apps/answers/crud/answers.py, src/apps/integrations/loris/api/applets.py, src/apps/integrations/loris/crud/user_relationship.py, src/apps/integrations/loris/domain.py, src/apps/integrations/loris/router.py, src/apps/integrations/loris/service/loris.py, src/apps/integrations/loris/tests/test_crud_relationship.py, src/apps/workspaces/service/check_access.py
Rework loris activity visits
🔗 [Jira Ticket M2-7316](https://mindlogger.atlassian.net/browse/M2-7316)
=> fix: rework answer visits EP (M2-7316)

src/apps/answers/api.py, src/apps/answers/crud/answers.py, src/apps/answers/domain/answers.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py
🔗 [Jira Ticket M2-7222](https://mindlogger.atlassian.net/browse/M2-7222)
- Add `submit_id` to check existence of answers for the case when created_at is the same for multiple answer uploads
=> fix: add submit_id for check-existence (M2-7222)

src/apps/answers/api.py, src/apps/answers/crud/answers.py, src/apps/answers/service.py, src/apps/shared/deps.py
🔗 [Jira Ticket M2-7502](https://mindlogger.atlassian.net/browse/M2-7502)
- add logs for /answers/check-existence
- add user_id check for /answers/check-existence
=> feat: add logs and user_id check for /answers/check-existence (M2-7502)

src/apps/answers/crud/answers.py, src/apps/answers/service.py, src/apps/integrations/loris/service/loris.py
Fixed issues with loading data into loris
🔗 [Jira Ticket M2-7403](https://mindlogger.atlassian.net/browse/M2-7403)
🔗 [Jira Ticket M2-7432](https://mindlogger.atlassian.net/browse/M2-7432)
🔗 [Jira Ticket M2-7322](https://mindlogger.atlassian.net/browse/M2-7322)
=> fix: Data is not uploaded to Loris (M2-7403)

src/apps/answers/service.py, src/apps/answers/tests/test_answers.py
Reverts ChildMindInstitute/mindlogger-backend-refactor#1528
=> Revert "fix: incorrect relation value when non admin is source and respondent but not target (M2-7517)"

.github/workflows/pr-open.yml, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py
Correction of PR #1528 but to correct release branch
=> fix: incorrect relation value when non admin is source and respondent but not target (M2-7517) 

src/apps/integrations/loris/service/loris.py
🔗 [Jira Ticket M2-7573](https://mindlogger.atlassian.net/browse/M2-7573)
=> fix: Added ability to send data only for chosen user (M2-7573)

src/apps/activity_assignments/crud/assignments.py, src/apps/activity_assignments/service.py, src/apps/activity_assignments/tests/test_assignments.py, src/apps/invitations/services.py, src/apps/mailing/static/templates/new_activity_assignments_en.html, src/apps/mailing/static/templates/new_activity_assignments_fr.html, src/config/service.py
Send email notification for new assignments or when user accept applet invitation
🔗 [Jira Ticket M2-7347](https://mindlogger.atlassian.net/browse/M2-7347)
=> feat: Send activity assignment emails notification (M2-7347)

src/apps/workspaces/domain/workspace.py, src/apps/workspaces/tests/test_workspaces.py
🔗 [Jira Ticket M2-7647](https://mindlogger.atlassian.net/browse/M2-7647)
- Add "useArbitrary" flag to workspace list
=> feat: Add arbitrary flag for workspace list (M2-7647)

src/apps/workspaces/api.py
🔗 [Jira Ticket M2-7647](https://mindlogger.atlassian.net/browse/M2-7647)
=> fix: Workspace list model conversion (M2-7647)

src/apps/answers/service.py, src/apps/workspaces/commands/arbitrary_server.py, src/infrastructure/utility/cdn_arbitrary.py, src/infrastructure/utility/cdn_client.py
🔗 [Jira Ticket M2-7582](https://mindlogger.atlassian.net/browse/M2-7582)
=> feat: Add arbitrary command to copy applet data (M2-7582)

src/apps/activities/domain/activity_item_base.py, src/apps/activities/tests/unit/domain/test_activity_item_create.py
🔗 [Jira Ticket M2-7653](https://mindlogger.atlassian.net/browse/M2-7653)
- Extend the list of item types for conditional logic summary
=> feat: Extend the list of item types for conditional logic summary (M2-7653)

compose/fastapi/Dockerfile, src/apps/activities/tests/fixtures/activities.py, src/apps/applets/tests/fixtures/applets.py
Hox fix for broken tests in develop branch
=> Fix: tests for Unity activity item

src/apps/integrations/api/integrations.py, src/apps/integrations/crud/integrations.py, src/apps/integrations/db/schemas.py, src/apps/integrations/errors.py, src/apps/integrations/router.py, src/apps/integrations/service/integrations.py, src/apps/integrations/tests/test_integrations.py
This PR depends on https://github.com/ChildMindInstitute/mindlogger-backend-refactor/pull/1548 being merged first!
🔗 [Jira Ticket M2-7428](https://mindlogger.atlassian.net/browse/M2-7428)
This PR:
* adds a new resources:
* adds a new resource to delete an existing integration from the Database.
1. run alembic: alembic upgrade head
2. run the backend
```bash
curl -X DELETE -L 'http://localhost:8000/integrations?type=LORIS&applet_id=44917af1-a9b2-43cd-aec2-4e8c8f7253ad' \
-H 'Accept: application/json, text/plain, */*' \
-H 'Accept-Language: en-US,en;q=0.9' \
-H 'Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZGE5NGVkMS01YmJiLTQ2MzItOGNlMi01MWIxMjZkMGQwMTMiLCJyanRpIjoiZmNjNzcwMmQtZmNhNS00NTdhLWE2N2ItMGNmMjEwNjk3MmMyIiwiZXhwIjoxNzI5ODM3NDczLCJqdGkiOiIzY …
```
=> Create endpoint for removing LORIS integration - Remove server connection (M2-7428)

.github/workflows/e2e-tests.yaml
This PR is to update the e2e test reporting workflow in the Slack channel test-results.  This update allows passing builds to populate the channel rather than only allowing failing builds.
🔗 [Jira Ticket M2-7838](https://mindlogger.atlassian.net/browse/M2-7838)
- An update to the e2e-tests yaml file to include an expanded workflow
=> [M2-7838] Add passed tests to the slack output steps

src/apps/answers/crud/answers.py, src/apps/answers/domain/answers.py, src/apps/answers/service.py, src/cli.py
**IMPORTANT: should be delivered with report server changes**
🔗 [Jira Ticket M2-7481](https://mindlogger.atlassian.net/browse/M2-7481)
=> chore: Change report server contract (M2-7481,M2-7483)

.github/workflows/run_build_deploy.yaml, .github/workflows/run_deploy_dev.yaml
- **Adding DR ECR**
- **extra output**
=> M2-7905 DR Add tag push stage to Github actions builds for DR ECR

src/apps/answers/domain/answers.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py
🔗 [Jira Ticket M2-8140](https://mindlogger.atlassian.net/browse/M2-8140)
This PR updates the following endpoints to add a nullable `sourceSubject` property to their `answer` objects
- Get activity answer: `GET /answers/applet/{applet_id}/activities/{activity_id}/answers/{answer_id}`
- Get flow submission: `GET /answers/applet/{applet_id}/flows/{flow_id}/submissions/{submit_id}`
The structure of the `sourceSubject` property is the same `SubjectReadResponse` as that returned from get subject endpoint (`GET /subjects/{subject_id}`). For example:
```json
{
"secretUserId": "string",
"nickname": "string",
"tag": "string",
"id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"lastSeen": "2024-11-04T14:52:16.183Z",
"appletId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"userId": …
```
=> feat: Add Source subject Details to endpoints that return individual answer submissions (M2-8140)

src/apps/activities/services/activity.py, src/apps/activity_flows/service/flow.py, src/apps/applets/service/applet.py, src/infrastructure/tests/unit/http/test_deps.py
Sync Release/1.9.0 back to [dev]
=> Release/1.9.0 [dev]

src/apps/activities/domain/conditions.py
=> Release/1.9.2 [main]

src/apps/answers/crud/answers.py, src/apps/answers/domain/answers.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py, src/apps/answers/tests/test_answers_arbitrary.py, src/apps/workspaces/crud/applet_access.py, src/apps/workspaces/domain/user_applet_access.py
🔗 [Jira Ticket M2-7255](https://mindlogger.atlassian.net/browse/M2-7255)
This PR adds extra fields to applet's data export. See ticket for more details
Currently, the FE ticket to add these changes to the actual reports isn't completed. To test these changes, make an authenticated request to  `/applet/{applet_id}/data`. Extra fields mentioned in the ticket should be present.
=> feat: Report answer export updates (M2-7255)

src/apps/activity_assignments/crud/assignments.py, src/apps/activity_assignments/service.py, src/apps/answers/domain/answer_items.py, src/apps/answers/domain/answers.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py, src/apps/subjects/domain.py
=> Release 1.9.3 [Main]

src/apps/answers/crud/answers.py, src/apps/answers/domain/answers.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py, src/apps/answers/tests/test_answers_arbitrary.py, src/apps/workspaces/crud/applet_access.py, src/apps/workspaces/domain/user_applet_access.py
This reverts commit 7abe7811b1e5ce6665d92a51ae3b9c46e0ee10e9 to remove from release 1.9.4
and include in a subsequent release after further testing.
=> Revert "feat: Report answer export updates (M2-7255) (#1670)"

src/apps/answers/crud/answers.py, src/apps/answers/domain/answers.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py, src/apps/answers/tests/test_answers_arbitrary.py, src/apps/workspaces/crud/applet_access.py, src/apps/workspaces/domain/user_applet_access.py
=> Release/1.9.4 [dev]

src/apps/answers/crud/answers.py, src/apps/answers/domain/answers.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py, src/apps/answers/tests/test_answers_arbitrary.py, src/apps/workspaces/crud/applet_access.py, src/apps/workspaces/domain/user_applet_access.py
This reverts commit 2cd996767c10f0c81e9ef10be33f1ad25f97243c from #1682
=> Reapply "feat: Report answer export updates (M2-7255) (#1670)"

.github/workflows/run_build_deploy.yaml, .github/workflows/run_deploy_dev.yaml, src/apps/subjects/api.py, src/apps/subjects/domain.py, src/apps/subjects/tests/tests.py, src/apps/workspaces/service/applet_access.py
=> Release/2025.01.1 [main]

src/apps/alerts/ws_api.py
Update applet.integrations check in ws_service
=> fix: update applet integrations check in ws_api

src/apps/alerts/ws_api.py
=> release/2025.01.2 [dev]

src/datadog.py
- Added env var to enable Datadog application profiling
Test on dev environment as there is a bug currently on Macs if this is enabled: https://github.com/DataDog/dd-trace-py/issues/12021
=> chore: Enable datadog profiler

src/apps/schedule/crud/events.py, src/apps/schedule/service/schedule_history.py
Fix a merge conflict introduced by hotfixes applied to the `release/2025.02.2` branch in #1747
=> sync 2025.02.2 -> dev

src/apps/shared/commands/patches/m2_8568_update_subscale_items_to_greek.py
🔗 [Jira Ticket M2-8568](https://mindlogger.atlassian.net/browse/M2-8568)
This PR changes a single character. I'm not even sure how to test it but I trust @rcmerlo does.
=> fix: spelling of "male" in Greek (M2-8568)

README.md, src/apps/answers/api.py, src/apps/answers/tests/conftest.py, src/apps/answers/tests/test_answers.py, src/apps/shared/commands/patches/m2_8568_update_subscale_items_to_greek.py
Merge `release/2025.03.1` to `dev`
=> Release/2025.03.1 [dev]

src/apps/shared/commands/patch_commands.py, src/apps/shared/commands/patches/m2_8175_library_cleanup_for_camhi.py
merge `release/2025.03.03` to `main`
=> Release/2025.03.3 [main]

src/infrastructure/dependency/structured_logs.py
- Fixed wrong logic for log level check
=> fix: log level logic

compose/fastapi/start-backend-datadog, copilot/mindlogger-backend/manifest.yml
Fix to enable structured logging on preview environments/Fargate
=> fix: Datadog startup and logging in preview envs

.github/workflows/_build.yaml, .github/workflows/_deploy.yaml, .github/workflows/run_build_deploy.yaml, .github/workflows/run_deploy_dev.yaml, compose/fastapi/Dockerfile, compose/fastapi/entrypoint, copilot/mindlogger-backend/manifest.yml, copilot/scripts/svc-deploy.sh, src/apps/file/test_file.py, src/datadog.py, src/infrastructure/database/migrations/env.py, src/infrastructure/database/migrations_arbitrary/env.py, src/infrastructure/dependency/structured_logs.py, src/infrastructure/http/exceptions.py
Merge `release/2025.04.1` to `main`
=> Release/2025.04.1 [main]

src/apps/activities/domain/response_type_config.py
🔗 [Jira Ticket M2-9039](https://mindlogger.atlassian.net/browse/M2-9039)
This PR adds the option for EHR items to be skippable.
This change can be properly tested once the corresponding changes in the admin panel are added.
=> feat: Add skippable option to EHR item type (M2-9039) 

.github/workflows/_deploy.yaml, src/apps/healthcheck/api.py, src/datadog.py, src/infrastructure/dependency/structured_logs.py, src/infrastructure/http/exceptions.py
- **chore: Added context to non-access logs**
- **Stack traces with errors**
- Errors are now logged with stack traces
- Other request context information added to general logging statements (client ip, request method, path, etc)
=> chore: Adding more context to log messages

src/apps/activities/domain/response_type_config.py
Merging `release/2025.04.4` to `main`
=> Release/2025.04.4 [main]

compose/fastapi/Dockerfile
- Added missing startup script that was in previous docker build
=> Added missing startup script

src/apps/answers/crud/answers.py, src/apps/answers/domain/answers.py, src/apps/answers/tests/test_answers.py, src/apps/answers/tests/test_answers_arbitrary.py
Merging `release/2025.05.1` to dev
=> Release/2025.05.1 [dev]

src/apps/invitations/domain.py, src/apps/mailing/static/templates/blocks/team_info_es.html, src/apps/mailing/static/templates/footers/footer_info_es.html, src/apps/mailing/static/templates/invitation_new_user_es.html, src/apps/mailing/static/templates/invitation_registered_user_es.html, src/apps/mailing/static/templates/new_activity_assignments_es.html, src/apps/mailing/static/templates/reset_password_es.html, src/apps/users/services/core.py
Adds Spanish language support to invitation emails and password reset functionality.
This includes adding the 'es' language option to the InvitationLanguage enum and creating new email templates for invitations and password resets in Spanish.
🔗 [Jira Ticket M2-9170](https://mindlogger.atlassian.net/browse/M2-9170)
=> feat: Adds support for Spanish language (M2-9170)

src/apps/integrations/oneup_health/api.py, src/apps/integrations/oneup_health/domain.py, src/apps/integrations/oneup_health/errors.py, src/apps/integrations/oneup_health/router.py, src/apps/integrations/oneup_health/service/oneup_health.py, src/apps/integrations/oneup_health/service/task.py, src/apps/integrations/oneup_health/tests/test_oneup_health.py, src/apps/integrations/oneup_health/tests/test_task.py, src/config/oneup_health.py
Merging `release/2025.05.4` to `main`
=> Release/2025.05.4 [main]

src/infrastructure/database/migrations/versions/2025_05_20_09_52-clean_up_subjects_is_deleted.py
Merging `release/2025.05.3` dev
=> Release/2025.05.3 [dev]

src/apps/answers/api.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py, src/apps/integrations/oneup_health/api.py, src/apps/integrations/oneup_health/service/domain.py, src/apps/integrations/oneup_health/service/ehr_storage.py, src/apps/integrations/oneup_health/service/oneup_health.py, src/apps/integrations/oneup_health/service/task.py, src/apps/integrations/oneup_health/tests/test_task.py
Curious [open source credit page](https://mindlogger.atlassian.net/jira/servicedesk/projects/MLA/knowledge/articles/340623543?spaceKey=MLA)
🔗 [Jira Ticket M2-9404](https://mindlogger.atlassian.net/browse/M2-9404)
- Includes `user_id` to ingestion process for more accurate data association.
=> feat: Adds user ID to EHR storage path (M2-9404)

compose/fastapi/start-backend-datadog
🔗 [Jira Ticket M2-9460](https://mindlogger.atlassian.net/browse/M2-9460)
Modified docker startup script to get CPU count and create 1 worker per CPU
=> chore: Added worker configuration to uvicorn startup

compose/fastapi/start-backend-datadog, src/apps/answers/api.py, src/apps/answers/crud/answers.py, src/apps/answers/service.py, src/apps/answers/tests/test_answers.py, src/apps/applets/service/applet.py, src/apps/integrations/oneup_health/api.py, src/apps/integrations/oneup_health/service/domain.py, src/apps/integrations/oneup_health/service/ehr_storage.py, src/apps/integrations/oneup_health/service/oneup_health.py, src/apps/integrations/oneup_health/service/task.py, src/apps/integrations/oneup_health/tests/test_task.py, src/apps/shared/commands/storage.py, src/cli.py
Merging `release/2025.06.4` to main
=> Release/2025.06.4 [main]

compose/fastapi/start-backend-datadog
Merging `release/2025.06.5` to main
This is an appendum to the 2025.06.4 releases
=> fix: Temp fix for workers (#1902)

src/apps/activities/db/schemas/activity_item.py, src/infrastructure/database/migrations/versions/2025_06_26_14_06-add_index_to_activty_items_activity_id.py
Curious [open source credit page](https://mindlogger.atlassian.net/jira/servicedesk/projects/MLA/knowledge/articles/340623543?spaceKey=MLA)
- Adds an index to the `activity_items.activity_id` column to improve query performance.
=> fix: Adds index to activity_items.activity_id

src/infrastructure/database/core.py
Curious [open source credit page](https://mindlogger.atlassian.net/jira/servicedesk/projects/MLA/knowledge/articles/340623543?spaceKey=MLA)
- [Thing]
=> fix: Disabling connection pooling

src/apps/applets/tests/unit/test_applet_crud.py
Curious [open source credit page](https://mindlogger.atlassian.net/jira/servicedesk/projects/MLA/knowledge/articles/340623543?spaceKey=MLA)
🔗 [Jira Ticket M2-9681](https://mindlogger.atlassian.net/browse/M2-9681)
- Fixed a unit test that broke with pytest-asyncio update
=> fix: Refactored unit test

.env.default, .github/workflows/pr-open.yml, .github/workflows/tests.yaml, docker-compose.yaml, src/apps/file/test_file.py, src/infrastructure/storage/cdn_arbitrary.py, src/infrastructure/storage/cdn_client.py, src/infrastructure/storage/storage.py, src/infrastructure/storage/tests/test_storage.py
🔗 [Jira Ticket M2-9793](https://mindlogger.atlassian.net/browse/M2-9793)
- Adding custom endpoint to S3 client setup
- Tests
=> fix: Adding endpoint URL to boto3 s3 client [M2-9793]

src/apps/mailing/static/templates/subjects/reset_password_es.txt
Changed the first letter of the Spanish email subject to a capital letter.
🔗 [Jira Ticket M2-9742](https://mindlogger.atlassian.net/browse/M2-9742)
=> fix: capital letter on spanish subject (M2-9742)
