ChildMindInstitute/mindlogger-backend-refactor

src/apps/applets/crud/applets.py
src/apps/applets/service/applet.py
src/apps/applets/tests/test_applet.py
src/apps/schedule/tests/test_schedule.py

Exclude applets from applet list in web and mobile without encryption
(password) after transfer ownership. It should avoid applets owner to answer on
questions from "not ready" applet.

M2-2282: Exclude applets without encryption for answers

---

src/apps/activities/crud/activity_history.py
src/apps/answers/crud/answers.py
src/apps/answers/service.py

Change logic for the getting answers for reports. Excldue answers on
performance tasks. New solution filters answers by available activity for
the report (added support for the arbitrary servers).

M2-4194: Exclude performance tasks from the reports

---

src/apps/activities/domain/response_values.py

Value is optional because after adding subscales can appear items with
response types 'singleSelect' and 'multiSelect' without value. In this
case we set value automatically

M2-4476: Make value is optional

---

conftest.py
src/apps/activities/crud/activity.py
src/apps/activities/crud/activity_history.py
src/apps/activities/crud/activity_item.py
src/apps/activities/crud/activity_item_history.py
src/apps/activities/domain/activity_item_base.py
src/apps/activities/domain/custom_validation.py
src/apps/activities/domain/response_values.py
src/apps/activities/domain/reusable_item_choices.py
src/apps/activities/domain/scores_reports.py
src/apps/activities/services/activity.py
src/apps/activities/services/activity_history.py
src/apps/activities/tests/fixtures/conditional_logic.py
src/apps/activities/tests/fixtures/configs.py
src/apps/activities/tests/fixtures/items.py
src/apps/activities/tests/fixtures/response_values.py
src/apps/activities/tests/fixtures/scores_reports.py
src/apps/activities/tests/unit/domain/test_activity_item_create.py
src/apps/activities/tests/unit/domain/test_custom_validation.py
src/apps/activities/tests/unit/domain/test_scores_reports.py
src/apps/activities/tests/utils.py
src/apps/applets/tests/test_applet_activity_items.py

- M2-4494: Fix error in alembic migrations downgrade
- M2-4493: Remove unused code in activities services, crud
- M2-4493: Add unit tests for domain validation, add base fixtures
- M2-4493: Add test to validate item name during appet updating

M2 4493 activity items tests

---

src/apps/transfer_ownership/service.py

https://mindlogger.atlassian.net/browse/M2-4895
https://mindlogger.atlassian.net/browse/M2-4896

M2-4896: remove new owners other roles, M2-4895: keep old owners' respondent role

---

src/apps/activities/domain/response_type_config.py
src/apps/activities/tests/unit/test_activity_item_change.py

resolves: M2-5008
Change default value of auto_advance flag for single selection item type. 
Since the implementation of the feature, requirements of the feature have changed, so the bug arose. 
New requirements: https://mindlogger.atlassian.net/wiki/spaces/MINDLOGGER1/pages/421199873/Auto-advance+setting+for+Single+Selection+Item+Type
Old requirements: https://mindlogger.atlassian.net/wiki/pages/viewpage.action?pageId=421199873&pageVersion=6

M2-5008: change the default value of auto-advance

---

src/apps/shared/commands/patch_commands.py
src/apps/shared/commands/patches/m2_5018_migrate_reviewer_respondents_list.py

resolves: [M2-5018](https://mindlogger.atlassian.net/browse/M2-5018)
Migration of user_applet_accesses and invitations records with role 'reviewer' adding subjects list
[M2-5018]: https://mindlogger.atlassian.net/browse/M2-5018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

M2-5018 Migrate reviewer respondent list to subject list

---

src/apps/activities/domain/response_type_config.py
src/apps/activities/tests/unit/test_activity_item_change.py
src/apps/shared/commands/patch_commands.py
src/apps/shared/commands/patches/m2_5045_auto_advance.py

resolves: M2-5045
Create patch command for setting auto_advance for  all the existing single selection items config to true, for all new items, false by default
Need to run command `python src/cli.py patch exec M2-5045` after deployment on each env

M2-5045: patch for setting auto_advance true for existing items, for new ones - false 

---

src/apps/users/domain.py
src/apps/users/tests/unit/test_user_domain.py

resolves: [M2-5109](https://mindlogger.atlassian.net/browse/M2-5109)
Replace InternalModel with PublicModel
Web has different SignUp comparing with admin panel and mobile version.
[M2-5109]: https://mindlogger.atlassian.net/browse/M2-5109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

M2-5109: Replace internal model with public model for UserCreateRequest

---

src/apps/invitations/crud.py
src/apps/invitations/domain.py

resolves: M2-4632
https://mindlogger.atlassian.net/browse/M2-4632
Change source for secret_user_id and nickname to subject instad of invitation

M2-4632: Change source for secret_user_id and nikname to subject

---

src/apps/workspaces/crud/user_applet_access.py

resolves: M2-4622
The correct result for obtaining respondent details (/workspaces/${ownerId}/applets/${appletId}/respondents/${respondentId}) should involve updating the secret user ID and nickname with data from the corresponding subject.

M2-4622: Change nickname source from user_applet_access to subject

---

src/apps/mailing/static/templates/blocks/write_us_en.html
src/apps/mailing/static/templates/reset_password_en.html

resolves: M2-5085
Update copy for reset password email
~Confirm if the new "Visit our Help Center" is correct.~
Seems to be correct because other emails also mention the use of the new URL

M2-5085: Update copy for reset password email

---

src/apps/activities/domain/response_values.py
src/apps/activities/errors.py
src/apps/activities/tests/unit/domain/test_activity_item_create.py

resolves: M2-4786
This PR introduces the "None of the above" option for multi-select fields, which allows users to deselect other options when this is selected.
Covered with unit test
Implemented with @childmindhirsch

M2-4786: none option added to multiSelect item type

---

src/apps/answers/service.py
src/apps/workspaces/api.py
src/apps/workspaces/domain/user_applet_access.py
src/apps/workspaces/service/user_applet_access.py
src/apps/workspaces/tests/test_workspaces.py

resolves: M2-4662
To add last_seen information into respondent info for EP which is used in the review tab in DataVis `/workspaces/{workspaceId}/applets/{appletId}/respondents/{respondentId}`
Review Date needs to default to the last date when any Activity in the Applet was completed if The Review Date and Activity and Response Time have not been selected

M2-4662:add last_seen to respondent_info

---

src/config/cors.py
src/middlewares/cors.py

resolves: [M2-5282](https://mindlogger.atlassian.net/browse/M2-5282)
Allow new frontend preview environment access API, setting a env vars like CORS__ALLOW_ORIGIN_REGEX=https:\/\/.*\.amplifyapp\.com  allowing amplify domain in CORS
AWS Amplify have a limitation do create sub subdomain in a custom domain, so it cannot create eg. pr-5282.admin.cmiml.net sub subdomain.
The subdomain for preview environment follow the pattern pr-<pr number>.<app id>.amplifyapp.com
[M2-5282]: https://mindlogger.atlassian.net/browse/M2-5282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

M2-5282: Add new env var to set allow_origin_regex CORS setting

---

src/apps/users/api/password.py
src/apps/users/services/core.py

🔗 [Jira Ticket M2-5203](https://mindlogger.atlassian.net/browse/M2-5203)
This PR updates the password recovery route, enabling the distinction between the web and admin frontends for the password reset email.
Currently when a forgot password request comes in, the link in the reset email is always pointing to the respondent web app. This changes that to make use of the `Mindlogger-Content-Source` HTTP header to distinguish between the two and use the proper link as configured in the settings.
To test this change, modify your `.env` file with the following values
```shell
SERVICE__URLS__FRONTEND__WEB_BASE="http://localhost:5173"
SERVICE__URLS__FRONTEND__ADMIN_BASE="http://localhost:3000"
```
1. Start up the API server and the admin web app.
2. Navigate to the forgot password page in the …

M2-5203: Distinguish between web and admin for password reset email

---

src/apps/users/tests/test_password.py
src/infrastructure/http/deps.py
src/infrastructure/http/domain.py

🔗 [Jira Ticket M2-5595](https://mindlogger.atlassian.net/browse/M2-5595)
This PR adds support for the mobile value of the `MindLogger-Content-Source` HTTP header. #1100 started making use of this HTTP header, but didn't account for the mobile value so this fixes that. I've also added a test case for it
Start up the API and the mobile app, and submit the forgot password form. You should be able to see the email at localhost:8085 pointing to the respondent web app password reset form (since the mobile app doesn't have this yet)
Make sure you have a `.env.dev` file in the mobile app folder, and not a `.env`

M2-5595: Error message appears when trying to reset password

---

src/apps/users/services/core.py
src/apps/users/tests/test_password.py

🔗 [Jira Ticket M2-5332](https://mindlogger.atlassian.net/browse/M2-5332)
This PR updates the password reset email subject line to read "Password reset", as suggested in the ticket.
> [!NOTE]
> Pay attention to the subject line
1. Start up the API server and the admin web app.
2. Navigate to the forgot password page in the admin web app
3. Enter your email address and send the request
4. Open the [local mailhog](http://localhost:8025/) and check the link in the email
**Expected outcome:** The subject line should say "Password reset"
5. Repeat steps 1-4 for the respondent web app

M2-5332: Update password reset email subject

---

src/apps/file/api/file.py
src/apps/file/test_file.py

🔗 [Jira Ticket M2-5810](https://mindlogger.atlassian.net/browse/M2-5810)
- Replace media bucket with the answers bucket for logs (like in old implementation)

M2-5810: Replace media bucket with the answers bucket for logs

---

src/apps/applets/service/applet.py
src/apps/applets/tests/fixtures/applets.py
src/apps/applets/tests/test_applet.py

(https://mindlogger.atlassian.net/jira/servicedesk/projects/MLA/knowledge/articles/340623543?spaceKey=MLA)
🔗 [Jira Ticket M2-5808](https://mindlogger.atlassian.net/browse/M2-5808)
- Save stream ip address, port, stream_enabled flag on applet creation
- Cover with test the case

M2-5808: fix saving stream ip address and port on new applet

---

src/apps/applets/commands/applet_ema.py

Add applet_id argument to ema export commands
- add -a (--applet_id) to applet-ema commands
- change job key for supporting multiple applet ids
Commands:
```
python src/cli.py applet-ema export-flows <date> -a <UUID>
python src/cli.py applet-ema export-flow-schedule <date> -a <UUID>
python src/cli.py applet-ema export-activity-schedule <date> -a <UUID>
```

M2-5876 Add applet_id argument to ema export commands

---

src/apps/answers/api.py
src/apps/answers/tests/test_answers.py

🔗 [Jira Ticket M2-5706](https://mindlogger.atlassian.net/browse/M2-5706)
Change format of admin secret id in data export from `[admin account] (<email>)` to `[admin account] (<secret id>)`

M2-5706 Change secret user id export format for admin respondent

---

src/apps/activities/tests/test_activities.py
src/apps/activities/tests/test_reusable_items.py
src/apps/alerts/test_alerts.py
src/apps/answers/tests/test_answer_for_cases.py
src/apps/answers/tests/test_answers.py
src/apps/answers/tests/test_answers_arbitrary.py
src/apps/applets/tests/test_applet.py
src/apps/applets/tests/test_applet_activity_items.py
src/apps/applets/tests/test_applet_folder.py
src/apps/applets/tests/test_applet_link.py
src/apps/applets/tests/test_applet_settings.py
src/apps/authentication/tests/test_auth.py
src/apps/file/test_file.py
src/apps/folders/test_folder.py
src/apps/invitations/test_invite.py
src/apps/library/tests.py
src/apps/schedule/tests/test_schedule.py
src/apps/shared/test/client.py
src/apps/test_data/test_data.py
src/apps/themes/tests.py
src/apps/transfer_ownership/tests.py
src/apps/users/tests/test_password.py
src/apps/users/tests/test_user.py
src/apps/workspaces/tests/test_workspaces.py

resolves: [M2-5331](https://mindlogger.atlassian.net/browse/M2-5331)
Replace the POST request for the `login` method of test client for API calls with generating access token and adding it to the client headers. It decrease API tests execution time on ~25-30%
[M2-5331]: https://mindlogger.atlassian.net/browse/M2-5331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

M2-5331: Replace login post request with generating token

---

Pipfile
Pipfile.lock
conftest.py
src/apps/applets/crud/applets.py
src/apps/applets/crud/applets_history.py
src/apps/applets/db/schemas/applet.py
src/apps/applets/service/applet.py
src/apps/applets/service/applet_history_service.py
src/apps/applets/tests/unit/test_applet_crud.py
src/apps/applets/tests/unit/test_applet_history_crud.py
src/apps/applets/tests/unit/test_history_mixin.py
src/apps/invitations/services.py
src/apps/schedule/service/schedule.py

resolves: [M2-5209](https://mindlogger.atlassian.net/browse/M2-5209)
Added tests to cover missing CRUDs.
Added nest-asyncio for request.getfixturevalue for async fixtures.
Need to refactor CRUDs. QueryParams should not be passed to the CRUD.
[M2-5209]: https://mindlogger.atlassian.net/browse/M2-5209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

M2 5209 tests for applet cruds

---

src/apps/activities/domain/response_values.py
src/apps/activities/tests/fixtures/response_values.py
src/apps/activities/tests/unit/domain/test_activity_item_create.py

🔗 [Jira Ticket M2-6057](https://mindlogger.atlassian.net/browse/M2-6057)
Drawing Values Request Format:
```
{
"drawingExample": "example.jpg",
"drawingBackground": "example.jpg",
"proportion": {
"enabled": true
}
}
```

M2-6057 Add proportion field for drawing item

---

.github/workflows/update-jira-tickets.yaml

🔗 [Jira Ticket M2-5922](https://mindlogger.atlassian.net/browse/M2-5922)
This PR introduces a GitHub Actions workflow that submits a list of ticket numbers to a Jira webhook based on a number of factors.
The workflow is triggered by a GitHub release, and it collates the list of Jira ticket numbers that were worked on since the last GitHub release that had a successful Jenkins build. It then waits for the outcome of the current build (trigged by the release) and submits that list of Jira tickets if the build is successful.
My original approach to this ticket was to modify the Jenkins scripts, but I changed that because it's much simpler to have this logic in one workflow (instead of being split across multiple CodeCommit repos), and we eventually intent to move CI/CD to GitHub Actions …

M2-5922: Create Update Jira Tickets GitHub Actions workflow

---

src/apps/activities/api/activities.py
src/apps/activities/crud/activity.py
src/apps/activities/filters.py
src/apps/activities/tests/test_activities.py
src/apps/answers/crud/answers.py
src/apps/answers/service.py

🔗 [Jira Ticket M2-5631](https://mindlogger.atlassian.net/browse/M2-5631)
Allows `/activities/applet/{applet_id}` to be filtered by `hasSubmitted` and `hasScore`.
`hasSubmitted` - Filter activities based on whether they have submitted any activities (Yes or No)
`hasScore` - Filter activities based on the availability of score (Yes or No)
1. Create a new applet with activity 
2. Call `/activities/applet/{applet_id}` endpoint with `hasSubmitted` it should return no results.
3. Add answers to this activity and run the same query again now it should return the activity that contains answers.
1. Create a new applet with activity but make sure to add a score to activity items.
2. Call `/activities/applet/{applet_id}` endpoint with `hasScore` it should return this new activity with the score …

M2-5631: Add hasScore and hasSubmitted filters to applet activities endpoint

---

src/apps/activities/api/activities.py
src/apps/activities/router.py
src/apps/activities/tests/test_activities.py
src/apps/applets/domain/applet.py
src/apps/applets/tests/fixtures/applets.py

🔗 [Jira Ticket M2-6075](https://mindlogger.atlassian.net/browse/M2-6075)
- Add new `/activity/flows/applet/{applet_id}` endpoint that returns combined activity and activity flows
- Add tests for `/activity/flows/applet/{applet_id}`
Example test step:
- Call API endpoint `/activity/flows/applet/{applet_id}` with an applet ID that contains activities and activity flows and you should see a combined result of activities and activity flows
Example output: https://gist.github.com/binho/7d1e03c686b83412e3ddc22b5b211e9c
PR #1166 should be merged first

M2-6075: Add new `/activity/flows/applet/{applet_id}` endpoint that returns combined activity and activity flows

---

.github/workflows/update-jira-tickets.yaml

This PR updates the Update Jira Tickets GH Actions workflow to fetch all commits before determining JIRA tickets. 
The current behavior is only using the most recent commit on the branch because the checkout action does a shallow clone by default. Therefore, we have to unshallow the clone in order to get all the commit messages. I decided to do it this way, instead of doing a deep clone from the outset because there are several exit points for the job that would render the deep clone unnecessary. So I do it at the point where it's needed
Compare the results of [the most recent release run](https://github.com/ChildMindInstitute/mindlogger-backend-refactor/actions/runs/8660113868/job/23747361824#step:7:17) to [this manual run](https://github.com/ChildMindInstitute/mindlogger-backend-refactor …

Update Jira Tickets 2

---

src/apps/subjects/api.py
src/apps/subjects/domain.py
src/apps/subjects/tests/tests.py

🔗 [Jira Ticket M2-6378](https://mindlogger.atlassian.net/browse/M2-6378)
This PR updates GET `/subjects/{subject_id}` to return more data in the form of the following fields:
- Applet ID
- Subject ID
Send an HTTP GET request to `/subjects/{subject_id}` with a valid Subject ID, and confirm that it returns the corresponding Applet ID and the Subject ID that was passed.
N/A

M2-6378: Update the Get Subjects endpoint to return more data

---

src/apps/answers/domain/answers.py
src/apps/answers/service.py
src/apps/answers/tests/test_answers.py

🔗 [Jira Ticket M2-6393](https://mindlogger.atlassian.net/browse/M2-6393)
- Add updated_at field to answer reviews list:
`GET /answers/applet/{applet_id}/answers/{answer_id}/reviews`

M2-6393 Add updated_at to answer reviews list

---

src/apps/applets/tests/fixtures/applets.py
src/apps/workspaces/crud/user_applet_access.py
src/apps/workspaces/tests/test_workspaces.py

🔗 [Jira Ticket M2-6457](https://mindlogger.atlassian.net/browse/M2-6457)
This PR is a simple change to account for multiple applets in the `/workspaces/{owner_id}/applets/{applet_id}/respondents/{respondent_id}` endpoint. The current implementation will return multiple results in an undefined order if the respondent being fetched has that role in multiple applets (and therefore has multiple entries in the `subjects` table).
By updating the join condition between `user_applet_accesses` and `subjects` to include both the `user_id` and `applet_id` columns, we ensure that the result set will have a single entry.
For manual testing, you'll need to create a workspace with two applets. Then, consume the `/workspaces/{owner_id}/applets/{applet_id}/respondents/{respondent_id}` endpoint with both …

M2-6457: Update the `/workspaces/{owner_id}/applets/{applet_id}/respondents/{respondent_id}` endpoint to account for multiple applets

---

src/apps/invitations/domain.py
src/apps/invitations/services.py
src/apps/invitations/test_invite.py

🔗 [Jira Ticket M2-6159](https://mindlogger.atlassian.net/browse/M2-6159)
Ensures `firstName`, `lastName`, `email`, and `title` fields are all available in the responses for each POST request:
- `invitations/{applet id}/managers`
- `invitations/{applet id}/reviewer`
Also ensures the `title` field propagates to the reviewer user account.
From http://127.0.0.1:8000/docs:
- Create a valid POST request to `invitations/{applet id}/managers`
**Expected outcome:** The fields `firstName`, `lastName`, `email` and `title` are all returned in the response.
- Create a valid POST request to `invitations/{applet id}/reviewer`
**Expected outcome:** The fields `firstName`, `lastName`, `email` and `title` are all returned in the response.
- Accept an invitation to a newly invited **Reviewer** and observe …

M2-6159: add missing fields to invitations

---

src/apps/file/domain.py

This PR doesn't have an associated ticket, I'll file one after opening in order to track this.
Currently, the `/file/upload-url` endpoint (eg, for adding image assets for Activity & Applet thumbnails) fails in local development environments. 
This is because the generated URLs (`http://localhost:9000/[path]/[to]/[image]`) fail pydantic's HttpUrl validation, with the given reason of "lacking a valid TLD", causing the endpoint to respond with an error. 
This PR swaps the validation performed from "HttpUrl" to "AnyHttpUrl", in order to allow `localhost` addresses to pass validation and return successfully.

Update `upload_url` validation

---

.github/workflows/oasdif.yaml

Update OASDIFF workflow to check api changes only when open PR against develope and main branches
This will avoid error checking during development in other branches and will not affect the main goal of this workflow, prevent breaking changes in production without being properly handle

chore: Update OASDIFF workflow to check api only on dev and main branches

---

src/apps/answers/service.py

Not returning lastSeen field when there are more then one respondent
🔗 [Jira Ticket M2-6553](https://mindlogger.atlassian.net/browse/M2-6553)

M2-6553 - Not returning lastSeen field when there are more then one respondent

---

src/apps/answers/service.py

Fixed bug on respondent list, it is not returning lastSeen field when there are more then one respondent
🔗 [Jira Ticket M2-6553](https://mindlogger.atlassian.net/browse/M2-6553)

M2-6553:  Not returning lastSeen field when there are more then one respondent

---

src/apps/subjects/api.py
src/apps/subjects/domain.py
src/apps/subjects/tests/tests.py

🔗 [Jira Ticket M2-6582](https://mindlogger.atlassian.net/browse/M2-6582)
This PR updates GET `/subjects/{subject_id}` to return more data in the form of the following fields:
- User ID
Send an HTTP GET request to `/subjects/{subject_id}` with a valid Subject ID, and confirm that it returns the User ID field. It should be null for limited accounts.
N/A

feat(mi): Add `userId` to get subjects query (M2-6582)

---

src/apps/answers/domain/answer_items.py

🔗 [Jira Ticket M2-6460](https://mindlogger.atlassian.net/browse/M2-6460)
- user_public_key in ItemAnswer DTO can be none
You can look into ItemAnswerCreate DTO here:  https://github.com/ChildMindInstitute/mindlogger-backend-refactor/blob/a68b0674c0204e849c1989e8629c8434967aa897/src/apps/answers/domain/answer_items.py#L61-L73

fix: user_public_key can be none (M2-6460)

---

src/apps/activities/domain/custom_validation_subscale.py
src/apps/activities/tests/unit/domain/test_custom_validation_subscale.py

🔗 [Jira Ticket M2-6726](https://mindlogger.atlassian.net/browse/M2-6726)
- Allow subscale score to be decimal, negative

bugfix: Allow subscale score to be decimal, negative (M2-6726)

---

.github/workflows/run_deploy_dev.yaml

added slack notifications feature

---

src/apps/shared/domain/response/core.py
src/apps/shared/ordering.py
src/apps/shared/test/base.py
src/apps/workspaces/api.py
src/apps/workspaces/crud/user_applet_access.py
src/apps/workspaces/router.py
src/apps/workspaces/service/workspace.py
src/apps/workspaces/tests/test_workspaces.py

🔗 [Jira Ticket M2-6664](https://mindlogger.atlassian.net/browse/M2-6664)
Adds support to order respondents and managers by encrypted fields (manager `first_name`, `last_name` & `email`, and respondent `nicknames`), and some fields that were not previously supported.
- Extended the `Ordering` class to support ordering by regular fields, as well as by encrypted fields conditional on # of records. Due to SQL decryption being a more expensive operation, ordering by encrypted fields is conditional on result set being small enough to not overload SQL server (currently set to 300 results).
- `respondents` & `managers` endpoints now also report which fields are supported for ordering via the `orderingFields` key in the response so that frontends can disable ordering on unsupported columns (in the …

fix(mi): support ordering by encrypted fields (M2-6664)

---

src/apps/answers/service.py
src/apps/answers/tests/test_answers.py

Update export data mapping, repondentId should be logged userId and respondentSecretId should be target user secret id
🔗 [Jira Ticket M2-6669](https://mindlogger.atlassian.net/browse/M2-6669)
🔗 [Jira Ticket M2-6557](https://mindlogger.atlassian.net/browse/M2-6557)

M2-6669 : Reports activity export update file to map to correct mi fields

---

src/apps/answers/crud/answers.py
src/apps/answers/service.py
src/apps/answers/tests/test_answers.py

🔗 [Jira Ticket M2-6616](https://mindlogger.atlassian.net/browse/M2-6616)
- Filter out incomplete submissions for `GET /answers/applet/{applet_id}/review/flows`
- Filter out incomplete submissions for `GET /answers/applet/{applet_id}/flows/{flow_id}/identifiers`
- Add `isCompleted` flag to the submission data for 
`GET /answers/applet/{applet_id}/flows/{flow_id}/submissions/{submit_id}`
- Add tests for the incomplete submission case for `GET /answers/applet/{applet_id}/flows/{flow_id}/submissions`

fix(flow-submission): Fix flow submission endpoints filtering out incomplete submissions(M2-6616)

---

src/apps/answers/crud/answers.py
src/apps/answers/filters.py
src/apps/answers/tests/test_answers.py

🔗 [Jira Ticket M2-6900](https://mindlogger.atlassian.net/browse/M2-6900)
- Make targetSubjectId as required filter for /answers/applet/{applet_id}/review/flows 
- Make targetSubjectId as required filter for /asnwers/applet/{applet_id}/review/activities
- Removed unused method

bugfix(summary-flows) targetSubjectId is required in query filters. (M2-6900)

---

src/apps/answers/domain/answers.py
src/apps/answers/service.py
src/apps/answers/tests/test_answers.py
src/apps/answers/tests/test_answers_arbitrary.py

🔗 [Jira Ticket M2-6282](https://mindlogger.atlassian.net/browse/M2-6282)
This PR updates the `/applet/{applet_id}/data` endpoint to provide the secret user ID of the source and target subjects in the exported data as `sourceSecretId` and `targetSecretId` respectively.
You should have an applet with some response data in it. Then go to https://localhost:8000/docs#/Answers/applet_answers_export_answers_applet__applet_id__data_get, plug in the applet ID, and inspect the data returned for the two new properties.
N/A

feat(mi): Add subject secret IDs to data export (M2-6282)

---

src/apps/shared/commands/patch_commands.py
src/apps/shared/commands/patches/m2_6757_replace_amp_sanitizer.py
src/apps/shared/domain/custom_validations.py

🔗 [Jira Ticket M2-6757](https://mindlogger.atlassian.net/browse/M2-6757)
- De sanitizing of &amp: to &

fix(sanitizing): Patch for ampersand desinitizing (M2-6757)

---

src/apps/answers/domain/answers.py
src/apps/answers/service.py
src/apps/answers/tests/test_answers.py

🔗 [M2-7002](https://mindlogger.atlassian.net/browse/M2-7002): [Overview] Nothing happens if select an item in the 'Recent Submissions' block
This PR makes a minor tweak to the existing `/answers/applet/{applet_id}/submissions` endpoint, to include `activityId` in the response fields for entries in the `submissions` array.
This is necessary for the frontend to generate the URL for linking to the Participant Details page for the specific activity data.
For an Applet with some response data…
1. Go to [localhost:8000/docs#/Answers/applet_submissions_list_answers_applet__applet_id__submissions_get](https://localhost:8000/docs#/Answers/applet_submissions_list_answers_applet__applet_id__submissions_get)
2. Plug in the applet ID, and inspect the data returned for the new properties.
[M2-6555]: …

feature(mi): Add `activityId` to applet submissions and stats endpoint (M2-7002)

---

src/apps/shared/commands/patches/m2_4611_add_answer_subjects.py

🔗 [Jira Ticket M2-7052](https://mindlogger.atlassian.net/browse/M2-7052)

fix(patch): skip not responding arbitrary servers for "answer update" patch (M2-7052)

---

src/apps/workspaces/commands/arbitrary_server.py
src/apps/workspaces/domain/workspace.py
src/apps/workspaces/service/workspace.py

🔗 [Jira Ticket M2-7021](https://mindlogger.atlassian.net/browse/M2-7021)

fix(cli): cli commands for not responding arbitrary servers (M2-7021)

---

.github/workflows/run_build.yaml
.github/workflows/run_deploy_dev.yaml

added steps to trigger ECS task
- [Thing]

added steps to trigger ECS task

---

src/apps/activity_flows/crud/flow_history.py
src/apps/activity_flows/domain/flow_full.py
src/apps/answers/service.py
src/apps/answers/tests/conftest.py
src/apps/answers/tests/test_answer_for_cases.py
src/apps/answers/tests/test_answers.py

🔗 [Jira Ticket M2-6851](https://mindlogger.atlassian.net/browse/M2-6851)
- Validation of submit_id for activity and flow submissions
Validation includes:
- submit_id uniqueness for activity submissions
- submit_id uniqueness for different flow submissions
- submit_id ordering in flow submissions:
```
Valid case of answers for activities for the flow with 3 activity:
1. answer_activity1
2. answer_activity2
3. answer_activity3
Invalid case#1:
1. answer_activity2
Invalid case#2:
1. answer_activity1
2. answer_activity3
```

chore(answers): add validation of submit_id (M2-6851)

---

src/apps/answers/service.py
src/apps/answers/tests/conftest.py
src/apps/answers/tests/test_answers.py

🔗 [Jira Ticket M2-6238](https://mindlogger.atlassian.net/browse/M2-6238)
- Activity sorting in summary fixed

fix: activity order mismatch (M2-6238)

---

src/apps/activities/crud/activity.py
src/apps/activities/domain/activity.py
src/apps/activities/services/activity.py

Adds `performance_task_type` and `is_performance_task` to the response of `/activities/applets/{appletId}`
🔗 [Jira Ticket M2-7091](https://mindlogger.atlassian.net/browse/M2-7091)
- Easier to test with the companion [Admin PR](https://github.com/ChildMindInstitute/mindlogger-admin/pull/1826)
- Perform a request to `/activities/applet/:appletId` and verify `performanceTaskType` and `isPerformanceTask` are present in `result.activitiesDetails[*]`
I decided to include the fields in this response as opposed to using `/workspace/{ownerId}/applets` or any of the other endpoints that already include these fields because this endpoint will eventually require filtering by `subjectId` [M2-6223](https://mindlogger.atlassian.net/browse/M2-6223) 
[M2-6223]: …

feat: add performance task fields to activities/applets (M2-7091)

---

src/apps/transfer_ownership/service.py
src/apps/transfer_ownership/tests.py

Missed to remove former owner "Team" tag in other fix, this impacts take now screens
🔗 [Jira Ticket M2-7134](https://mindlogger.atlassian.net/browse/M2-7134)

fix: Missing removal former owner team tag after transfer owner (M2-7134)

---

src/apps/answers/service.py
src/apps/answers/tests/conftest.py
src/apps/answers/tests/test_answers.py

🔗 [Jira Ticket M2-7213](https://mindlogger.atlassian.net/browse/M2-7213)
- Fix validation for flow submissions when flow contains same activity multiple times

fix: Allow answers for flow containing same activity multiple times (M2-7213)

---

Pipfile
Pipfile.lock
src/apps/shared/commands/patch_commands.py
src/apps/shared/commands/patches/m2_7203_migrate_secret_ids.py

🔗 [Jira Ticket M2-7203](https://mindlogger.atlassian.net/browse/M2-7203)
- Patch to migrate missed secret ids for `user_applet_accesses` and `subjects` where `secret_user_id = '#deleted#'`
Patch requires next env variables to be set:
```
MONGO_URI=mongodb+srv://name:pass@host
MONGO_DB=test
```
CLI command:
```
MONGO_URI=<uri> MONGO_DB=<db_name> python src/cli.py patch exec  M2-7203
```

chore: Create patch to migrate missed secret ids (M2-7203)

---

src/apps/answers/service.py
src/apps/answers/tests/test_answers.py
src/apps/subjects/crud/subject.py
src/apps/workspaces/crud/user_applet_access.py

Fix a ISE (500) on latest submissions endpoint when subjects had been deleted after send any answer
Solution:
Duplicate queries returning subjects by id or user_ids (because it is used in many places) and removed filter is_deleted = false in those new queries
🔗 [Jira Ticket M2-7308](https://mindlogger.atlassian.net/browse/M2-7308)

Fix: Error returning latest submission when there is a deleted subject (M2-7308)

---

src/apps/authentication/deps.py
src/apps/healthcheck/api.py
src/apps/healthcheck/domain.py
src/apps/healthcheck/router.py
src/apps/healthcheck/tests.py

🔗 [Jira Ticket M2-7094](https://mindlogger.atlassian.net/browse/M2-7094)
- Endpoint `POST /emengency-message` for forced updates and notifications to enable the display of system messages and notifications managed from the backend on mobile devices

feat: Implement emergency message endpoint (M2-7094)

---

src/apps/invitations/api.py
src/apps/invitations/services.py
src/apps/subjects/api.py
src/apps/workspaces/crud/user_applet_access.py
src/apps/workspaces/service/user_applet_access.py

if a pinned user got deleted, its not delete rows in user_pins table.  Causing an error if you try to accept a new invitation for same user and it is pinned again.
🔗 [Jira Ticket M2-#](https://mindlogger.atlassian.net/browse/M2-7326)

Fix: Error when accepting an invitation for former deleted and pinned users (M2-7326)

---

src/apps/activities/domain/activity_item_base.py
src/apps/activities/domain/custom_validation.py
src/apps/activities/domain/response_type_config.py
src/apps/activities/domain/response_values.py
src/apps/activities/tests/fixtures/configs.py
src/apps/activities/tests/fixtures/items.py
src/apps/answers/domain/answers.py
src/apps/applets/tests/test_applet_activity_items.py

🔗 [Jira Ticket M2-7239](https://mindlogger.atlassian.net/browse/M2-7239)
Adds support to `paragraphText` item type
- Added new ParagraphItem
This is currently working with the latest [admin version in develop](https://github.com/ChildMindInstitute/mindlogger-admin/pull/1863)
and a specific branch in the [web app](https://github.com/ChildMindInstitute/mindlogger-web-refactor/pull/512)
- I am still looking at how [Pedantic](https://docs.pydantic.dev/latest/) is being used. I had some issues with some attributes that I copied from the Text item but after removing those a correct behavior from the resources was returned.
- I am also taking a look at the way the tests in pytests have been implemented and hopefully upcoming PRs will have tests. For now this one does not seem to …

feat: added new Paragraph Item in the backend by copying all Text Item coincidences in the code (M2-7239)

---

src/apps/answers/service.py
src/apps/answers/tests/test_answers.py

🔗 [Jira Ticket M2-7517](https://mindlogger.atlassian.net/browse/M2-7517)
- add an additional check for the get_answer_relation function to check for a temp relation if it is a temp relation we return "other"
- other than that we keep going with our code execution
- Jira ticket include the testing steps make sure to follow them and check for the final output

fix: incorrect relation value when non admin is source and respondent but not target (M2-7517)

---

src/apps/activities/domain/activity_base.py

🔗 [Jira Ticket M2-7285](https://mindlogger.atlassian.net/browse/M2-7285)
This PR fixes a crash caused by the introduction of the `auto_assign` field on Activities (original PR #1511). The model previously didn't align with the ORM definition.
- From the Dashboard, try to edit any Applet.
**Expected outcome:** The Applet should load properly into the builder, and **not** cause this BE error in DevTools:

fix: allow `auto_assign` field to be `None` (M2-7285)

---

src/apps/activity_flows/domain/base.py

Fixing error introduced in M2-7285 when auto-assign field is null for activity flow
🔗 [Jira Ticket M2-7285](https://mindlogger.atlassian.net/browse/M2-7285)

fix: Hot fix for null auto-assign field in activity flow (M2-7285)

---

src/apps/activities/services/activity.py
src/apps/activity_flows/service/flow.py
src/apps/applets/domain/applets/public_detail.py
src/apps/applets/tests/test_applet.py

🔗 [Jira Ticket M2-7391](https://mindlogger.atlassian.net/browse/M2-7391)
This PR updates the applet update endpoint `PUT /applets/{applet_id}` to update the `auto_assign` flag on the activities in the applet, if that flag is present in the update payload.
- Update `ActivityService#update_create` to update activities' `auto_assign` flag.
There is no UI yet, so this has to be tested via Postman:
1. Create an applet with some activities (This will create activities with `auto_assign` defaulted to `true`)
2. Update the applet and set `auto_assign` on some activities to `false`
The change to that applet's activities' `auto_assign` should now be properly persisted.
N/A

feat: update applet activities auto_assign (M2-7391)

---

src/apps/activities/crud/activity_history.py
src/apps/activities/domain/activity.py
src/apps/activities/domain/activity_create.py
src/apps/activities/domain/activity_update.py
src/apps/activities/services/activity.py
src/apps/activity_assignments/api.py
src/apps/activity_assignments/crud/assignments.py
src/apps/activity_assignments/domain/assignments.py
src/apps/activity_assignments/router.py
src/apps/activity_assignments/service.py
src/apps/activity_assignments/tests/test_assignments.py
src/apps/activity_flows/domain/flow.py
src/apps/activity_flows/service/flow.py
src/apps/answers/domain/answers.py
src/apps/applets/domain/applet_create_update.py
src/apps/subjects/api.py
src/apps/subjects/domain.py
src/apps/subjects/tests/tests.py
src/infrastructure/app.py
src/middlewares/content_length.py

Added new GET endpoint `/users/me/assignments/applet/{applet_id}` to return all activity assigned as respondent for logged user
- Also removed some mypy warnings
🔗 [Jira Ticket M2-7275](https://mindlogger.atlassian.net/browse/M2-7275)

feat: Add new endpoint to return activity assignment for logged user (M2-7275)

---

src/apps/answers/crud/answers.py
src/apps/answers/db/schemas.py
src/apps/answers/domain/answers.py
src/apps/answers/service.py
src/apps/workspaces/commands/arbitrary_server.py
src/infrastructure/utility/cdn_client.py

🔗 [Jira Ticket M2-7674](https://mindlogger.atlassian.net/browse/M2-7674)
- CLI command to check (/remove) copied from one server to another one  applet data
```
python src/cli.py arbitrary check-copied-applet-answers -s <source arbitrary server owner email> -t <target arbitrary server owner email> <applet_id_1> <applet_id_2> ... <applet_id_n> --delete
```

feat: Add arbitrary command to check-delete copied applet data (M2-7674)

---

src/apps/applets/commands/__init__.py
src/apps/applets/commands/applet.py
src/apps/transfer_ownership/service.py
src/cli.py

🔗 [Jira Ticket M2-7719](https://mindlogger.atlassian.net/browse/M2-7719)
- Command to transfer applet ownership
```
python src/cli.py applet transfer-ownership -s <user_from_email> -t <user_to_email> applet_id1 applet_id2 ... applet_idN
```

feat: Create cli command to transfer applet ownership (M2-7719)

---

src/apps/activities/api/activities.py
src/apps/activities/crud/activity.py
src/apps/activities/domain/activity.py
src/apps/activities/services/activity.py
src/apps/activities/tests/test_activities.py

🔗 [Jira Ticket M2-7475](https://mindlogger.atlassian.net/browse/M2-7475)
Adds missing `items` property to activities returned by the [recently added](https://github.com/ChildMindInstitute/mindlogger-backend-refactor/pull/1565) `/activities/applet/{applet_id}/subject/{subject_id}` endpoint. Item information is needed for every activity in the Admin App's dashboard section to determine whether the activity is eligible for Take Now (some item types are mobile-only).
- Test the `/activities/applet/{applet_id}/subject/{subject_id}` endpoint and observe the result
**Expected outcome:** Each activity in the `activities` array now also contains an `items` array representing the item data for that activity
The **OASDIFF breaking changes** check failed due to some now-missing properties returned by …

fix: add `items` to assigned activities endpoint (M2-7475)

---

src/apps/activities/api/activities.py
src/apps/activities/tests/test_activities.py
src/apps/activity_assignments/api.py
src/apps/activity_assignments/crud/assignments.py
src/apps/activity_assignments/service.py
src/apps/shared/query_params.py

🔗 [Jira Ticket M2-6223](https://mindlogger.atlassian.net/browse/M2-6223)
Assignments being returned by the recently added `/activities/applet/{applet_id}/subject/{subject_id}` endpoint were only matching by respondent subject, but the AC for M2-6223 states to return assignments matching either by respondent _or_ target subject. Fixed this behaviour and updated tests to verify this is working as intended.
In addition, the `check_for_assignment_and_notify` function was using a CRUD function `get_by_respondent_subject_id` to return assignments matching a given respondent subject, which did not perform soft-delete integrity checks. This caused email notifications sent to pending full accounts after they've accepted the invitation to include unassigned activities. A better function to use is …

fix: Return assignments matching either respondent or target subject ID (M2-6223)

---

src/apps/activities/services/activity.py
src/apps/activity_assignments/crud/assignments.py
src/apps/activity_assignments/service.py
src/apps/activity_flows/service/flow.py
src/apps/applets/tests/conftest.py
src/apps/applets/tests/test_applet.py

On applet update, if an activity or flow got deleted, soft deleted activity assignments associates for those activites/flows
🔗 [Jira Ticket M2-7640](https://mindlogger.atlassian.net/browse/M2-7640)

feature: Soft delete activity assignments on activity/flow deletion

---

src/apps/activities/domain/custom_validation_subscale.py
src/apps/activities/domain/scores_reports.py
src/apps/activities/errors.py
src/apps/activities/tests/fixtures/scores_reports.py
src/apps/applets/tests/test_applet_activity_items.py

🔗 [Jira Ticket M2-7586](https://mindlogger.atlassian.net/browse/M2-7586)
This PR updates the validation for the subscale lookup table to support ranges in the `age` field using the tilde character (~), similar to the `score` and `rawScore` fields.
Consume the create applet endpoint, where the data contains a subscale lookup table with an age range
> [!NOTE]
> Edit the `email` and `password` variables
```shell
email=""
password=""
login_response=$(curl 'https://localhost:8000/auth/login' \
-H 'Content-Language: en-US' \
-H 'Content-Type: application/json' \
-H 'Mindlogger-Content-Source: admin' \
-s --data-raw "{\"email\":\"${email}\",\"password\":\"${password}\"}")
access_token=$(echo "${login_response}" | jq -r '.result.token.accessToken')
workspace_id=$(echo "${login_response}" | jq -r …
```

feat: Update Subscale Lookup Table to support age ranges (M2-7586)

---

src/apps/activity_assignments/crud/assignments.py
src/apps/activity_assignments/service.py
src/apps/answers/crud/answers.py
src/apps/answers/service.py
src/apps/subjects/api.py
src/apps/subjects/domain.py
src/apps/subjects/router.py
src/apps/subjects/services/subjects.py
src/apps/subjects/tests/tests.py
src/apps/workspaces/service/check_access.py

🔗 [Jira Ticket M2-7919](https://mindlogger.atlassian.net/browse/M2-7919)
This PR creates the new endpoint `/subjects/respondent/{respondent_subject_id}/activity-or-flow/{activity_or_flow_id}`, which returns a list of subjects based on an association with the respondent subject and activity/flow specified. The endpoint is accessible by users with the following applet roles:
- Owner
- Manager
- Coordinator
- Reviewer (who is assigned the `respondent_subject_id` subject)
Each subject in the list returned will be the target subject of at least one:
- Assignment where `respondent_subject_id` is the respondent subject (including auto-assigned activities/flows)
- Submission where `respondent_subject_id` is the source subject
The return type is `TargetSubjectByRespondentResponse`, and here's a …

feat: Get Subjects by Respondent Subject: Submissions + Assignments (M2-7919)

---

.github/workflows/e2e-tests.yaml

This PR fixes a syntax error in the `e2e-tests.yaml` file that is breaking the "Preview and Test PR" workflow
N/A
N/A

chore: Fix syntax error in e2e-tests.yaml

---

Makefile
docker-compose.yaml
src/apps/activities/api/activities.py
src/apps/activities/router.py
src/apps/activities/tests/test_activities.py
src/apps/answers/crud/answers.py
src/apps/answers/service.py
src/apps/applets/tests/fixtures/applets.py
src/apps/subjects/api.py

This PR is exactly the same as https://github.com/ChildMindInstitute/mindlogger-backend-refactor/pull/1614 except this PR is for the respondent activities/flows endpoint.
The respondent endpoint returns activities/flows that:
* Have `auto_assign` of `True`
* Have `auto_assign` of `False` AND have an assignment whose `respondent_subject_id` is the subject ID in the request
* Have answers whose `source_subject_id` is the subject ID in the request
🔗 [Jira Ticket M2-M2-7854](https://mindlogger.atlassian.net/browse/M2-7854)
TBD
N/A

feat: Add endpoint to get activities/flows assigned to or submitted for respondent (M2-7854)

---

src/apps/applets/api/applets.py
src/apps/applets/domain/applet_create_update.py
src/apps/applets/router.py
src/apps/applets/service/applet.py
src/apps/applets/tests/test_applet.py

🔗 [Jira Ticket M2-7830](https://mindlogger.atlassian.net/browse/M2-7830)
This PR updates the applet duplication endpoint to optionally include a `include_report_server` property that defaults to false (making it backwards compatible).
The following properties are duplicated:
- `reportServerIp`
- `reportPublicKey`
- `reportIncludeUserId`
- `reportIncludeCaseId`
- `reportEmailBody`
Update the `email`, `password`, and `api_base_url` variables and then run the following shell script
```shell
email=""
password=""
api_base_url="https://localhost:8000"
login_response=$(curl "${api_base_url}/auth/login" \
-H 'Content-Language: en-US' \
-H 'Content-Type: application/json' \
-H 'Mindlogger-Content-Source: admin' \
-s --data-raw "{\"email\":\"${email}\",\"password\":\"${password}\"}"
) …
```

feat(applet-duplication): add optional report server config flag (M2-7830)

---

src/apps/activity_assignments/service.py
src/apps/activity_assignments/tests/test_assignments.py
src/apps/answers/service.py
src/apps/invitations/domain.py
src/apps/invitations/services.py
src/apps/invitations/test_invite.py
src/apps/mailing/services.py
src/apps/mailing/static/templates/blocks/team_info_en.html
src/apps/mailing/static/templates/blocks/team_info_fr.html
src/apps/mailing/static/templates/footers/footer_info_en.html
src/apps/mailing/static/templates/footers/footer_info_fr.html
src/apps/mailing/static/templates/header.html
src/apps/mailing/static/templates/invitation_new_user_el.html
src/apps/mailing/static/templates/invitation_new_user_en.html
src/apps/mailing/static/templates/invitation_new_user_fr.html
src/apps/mailing/static/templates/invitation_registered_user_el.html
src/apps/mailing/static/templates/invitation_registered_user_en.html
src/apps/mailing/static/templates/invitation_registered_user_fr.html
src/apps/mailing/static/templates/new_activity_assignments_el.html
src/apps/mailing/static/templates/new_activity_assignments_en.html
src/apps/mailing/static/templates/new_activity_assignments_fr.html
src/apps/mailing/static/templates/reset_password_en.html
src/apps/mailing/static/templates/transfer_ownership_registered_user_en.html
src/apps/mailing/static/templates/transfer_ownership_unregistered_user_en.html
src/apps/transfer_ownership/service.py
src/apps/users/services/core.py
src/apps/users/tests/fixtures/users.py

🔗 [Jira Ticket M2-7665](https://mindlogger.atlassian.net/browse/M2-7665)
This PR adds Greek email templates for account invitation and activity assignment emails.
TBD
~~The Greek templates are currently missing actual Greek translations. So they are effectively copies of the English templates. After receiving actual translations I'll update this PR before merging.~~
The corresponding Admin App PR is here: https://github.com/ChildMindInstitute/mindlogger-admin/pull/1945

feat: add Greek email templates (M2-7665)

---

src/apps/activities/domain/scores_reports.py
src/apps/applets/tests/test_applet_activity_items.py

Quick fix for ScoringType definition using enum.StrEnum instead of str, ENUM.

fix: Fixed ScoringType class using new python Enum syntax

---

src/apps/activities/domain/custom_validation.py
src/apps/activities/tests/fixtures/items.py
src/apps/activities/tests/fixtures/response_values.py
src/apps/applets/tests/test_applet_activity_items.py

As an Admin, I want to choose the paragraph item type as a response phrase field so that I can include its contents in my Action Plan. By adding paragraph option to the allowed types on validate_phrasal_templates, the backend can store Activities with PhrasalBuilder Items that contain Parragraph items as elements of the PhraseBuilder item. 
🔗 [Jira Ticket M2-7762](https://mindlogger.atlassian.net/browse/M2-7762)
- [Allow new item_type (paragraph) to phrase-builder response options]
ADMIN PANEL - CONFIGURATION
Creating Activity with paragraph type on Phrase Builder
WEB APPLICATION: 
ADMIN PANEL -  RESULTS
* Create an activity
* Create and item  of type parragraph inside your activity
* In the same activity create a new item of type phrase builder
* Phrase builder should …

feature: paragraph ItemResponseType for phrase builder response options BE (M2-7762)

---

src/apps/activities/domain/custom_validation.py

🔗 [Jira Ticket M2-8147](https://mindlogger.atlassian.net/browse/M2-8147)
This PR updates the applet validation logic to allow items of type `NUMBERSELECT` to be included in the report or section printed items.
- Follow the steps in https://github.com/ChildMindInstitute/mindlogger-admin/pull/1966 and save the applet again at the end
- Confirm that the applet is saved successfully, and check the `activities.scores_and_reports` column in the database to confirm the presence of the `age_screen` item
N/A

fix: Allow number select item type to be printed (M2-8147)

---

src/apps/activities/api/activities.py
src/apps/activities/tests/test_activities.py
src/apps/applets/api/applets.py
src/apps/applets/domain/applet.py
src/apps/applets/service/applet.py
src/apps/applets/tests/test_applet.py
src/apps/subjects/services/subjects.py

🔗 [Jira Ticket M2-8164](https://mindlogger.atlassian.net/browse/M2-8164)
🔗 [Jira Ticket M2-8026](https://mindlogger.atlassian.net/browse/M2-8026)
This change adds `respondentMeta` to the response for `GET /applets/{applet_id}/base-info` to provide the Web App with the current respondent's subject ID, which is required to determine if a previous submission is a self-report in order to fix the bug reported by M2-8164.
To note: `respondentMeta` is already provided in two other existing endpoints, but not by ones consumed by the Web App. To ensure uniformity of this data structure across all three endpoints, created a function `SubjectsService.to_respondent_meta` and reused it in all 3 places.
<details>
<summary>Example response</summary>
```json
{
"result": {
"displayName": "Applet 3", …
```

fix: Add respondent subject metadata to applet base info (M2-8164, M2-8026)

---

src/apps/activity_assignments/crud/assignments.py
src/apps/activity_assignments/service.py
src/apps/answers/domain/answer_items.py
src/apps/answers/domain/answers.py
src/apps/answers/service.py
src/apps/answers/tests/test_answers.py
src/apps/subjects/domain.py

🔗 [Jira Ticket M2-8214](https://mindlogger.atlassian.net/browse/M2-8214)
This PR fixes an issue whereby when starting, but not completing, Take Now between two subjects, then letting the temporary relation expire (24 hours in production, or 5 minutes in other environments), it was subsequently not possible for the respondent subject to complete an assessment on the target subject via a valid activity assignment. The submission was being rejected by the BE because it only found an expired temporary relation and threw an error.
To fix, the BE now checks if there's an existing activity assignment between the respondent and the target before concluding that the submission is invalid due to an expired temporary relation.
In making this change, also cleaned up some typing in some entity types …

fix: Incomplete Take Now flow prevents multi-informant assignment (M2-8214)

---

src/apps/subjects/api.py
src/apps/subjects/domain.py
src/apps/subjects/tests/tests.py
src/apps/workspaces/service/applet_access.py

🔗 [Jira Ticket M2-8464](https://mindlogger.atlassian.net/browse/M2-8464)
This PR updates the structure of the subjects being returned by the "Get target subjects by respondent" endpoint. Each subject now includes a `teamMemberCanViewData` property, which indicates whether the logged-in admin user calling the endpoint can view the data of that particular subject.
Test along with https://github.com/ChildMindInstitute/mindlogger-admin/pull/2009
N/A

feat: Update "Get target subjects by respondent" endpoint to include `teamMemberCanViewData` property (M2-8464)

---

.github/workflows/run_build_deploy.yaml
.github/workflows/run_deploy_dev.yaml

This is a quick PR to fix the [recent deployment failures](https://github.com/ChildMindInstitute/mindlogger-backend-refactor/actions/runs/12677880597/job/35350024013) to dev. It bumps `aws-actions/amazon-ecs-deploy-task-definition` from v1 to v2.
I did a quick search and there doesn’t appear to have been any recent changes to either the task definition in ECS or the workflow file [run_deploy_dev.yaml](https://github.com/ChildMindInstitute/mindlogger-backend-refactor/blob/develop/.github/workflows/run_deploy_dev.yaml) in GitHub.
I found [this GitHub issue](https://github.com/aws-actions/amazon-ecs-deploy-task-definition/issues/705) that also doesn’t hint at a cause, but the consensus is that upgrading `aws-actions/amazon-ecs-deploy-task-definition` from v1 to v2 fixes the issue.
We can …

chore: Bump aws-actions/amazon-ecs-deploy-task-definition from v1 to v2

---

src/apps/subjects/api.py
src/apps/subjects/domain.py
src/apps/subjects/router.py
src/apps/subjects/tests/tests.py
src/apps/workspaces/crud/user_applet_access.py
src/apps/workspaces/domain/workspace.py
src/apps/workspaces/service/check_access.py
src/apps/workspaces/service/user_applet_access.py
src/apps/workspaces/tests/test_workspaces.py

🔗 [Jira Ticket M2-8465](https://mindlogger.atlassian.net/browse/M2-8465)
This PR updates the get workspace respondents endpoints to add a `roles` property to each object in the `details` array. The `roles` property contains a list of roles the user has in a particular applet. This affects these endpoints:
- Workspace respondents list - `/workspaces/{owner_id}/respondents`
- Workspace applet respondents list -  `/workspaces/{owner_id}/applets/{applet_id}/respondents`
I've also added a `roles` property to each subject returned from these endpoints:
- Get subject - `/subjects/{subject_id}`
- Get target subjects by respondent - `/subjects/respondent/{respondent_subject_id}/activity-or-flow/{activity_or_flow_id}`
Use the `/docs` endpoint to call each endpoint and confirm that the roles being …

feat: Update the workspace applet respondents list endpoint to include each respondent's role (M2-8465)

---

src/apps/answers/crud/answer_items.py
src/apps/answers/crud/answers.py
src/apps/answers/filters.py
src/apps/answers/tests/test_answers.py
src/apps/answers/tests/test_answers_arbitrary.py

🔗 [Jira Ticket M2-8215](https://mindlogger.atlassian.net/browse/M2-8215)
🔗 [Jira Ticket M2-7348](https://mindlogger.atlassian.net/browse/M2-7348)
This PR adds optional filtering by activity or flow id to the applets dates endpoint via the `activityOrFlowId` parameter.
If the parameter is provided, the BE automatically determines which of the two is given, and filters accordingly.
To test this, providing the `activityOrFlowId` parameter to the `/answers/applet/{applet_id}/dates` suffices. This can be tested providing either of the two (activity/flow ID)
Since this is an optional parameter, previous behavior isn't affected.

feature: Activity/Flow id dates filtering (M2-8215)(M2-7348)

---

src/apps/activities/domain/response_type_config.py
src/apps/activities/tests/fixtures/configs.py
src/apps/activities/tests/unit/test_activity_item_change.py
src/apps/jsonld_converter/service/document/field.py
src/apps/jsonld_converter/service/export/activity_item.py
src/apps/test_data/service.py

🔗 [Jira Ticket M2-8690](https://mindlogger.atlassian.net/browse/M2-8690)
This change allows Single Selection item type to have the `response_data_identifier` configuration property, which up till now has only been supported by the Short Text item type.
1. From FastAPI Swagger UI or Postman, authenticate then do a POST with this body to `/workspaces/{your_user_id}/applets` where `{your_user_id}` is replaced with an admin user's ID. (Hopefully it works, not sure if the `encryption` is user-specific?)
<details>
<summary>Expand for JSON</summary>
<pre>
{
"displayName": "Applet",
"description": {
"en": ""
},
"themeId": null,
"about": {
"en": ""
},
"image": "",
"watermark": "",
"activities": [
{
"name": "Activity",
"description": {
"en": ""
},
"showAllAtOnce": false,
"isSkippable": false, …

feat: Allow designating Single Selection items as response data identifiers (M2-8690)

---

src/apps/schedule/crud/events.py
src/apps/schedule/service/schedule.py
src/apps/schedule/service/schedule_history.py

🔗 [Jira Ticket M2-8494](https://mindlogger.atlassian.net/browse/M2-8494)
🔗 [Jira Ticket M2-8717](https://mindlogger.atlassian.net/browse/M2-8717)
🔗 [Jira Ticket M2-8725](https://mindlogger.atlassian.net/browse/M2-8725)
This PR fixes the following issues:
- After adding a new activity to an applet, its entry to `applet_events` uses the old applet version number
- Adding a new scheduled event for an activity/flow removes all its previous scheduled event(s). There can be only one "always available" event, whereas many scheduled events per activity/flow should be allowed
- In the *notification_histories* table, the *is_deleted* column doesn't become `true` after removing the notification from the event
- In the *reminder_histories* table, the *is_deleted* column doesn’t become `true` after …

fix: Scheduling History Logic Fixes (M2-8494) (M2-8717) (M2-8725)

---

src/apps/activities/services/activity.py
src/apps/activity_flows/service/flow.py
src/apps/applets/commands/applet_ema.py
src/apps/schedule/crud/events.py
src/apps/schedule/db/schemas.py
src/apps/schedule/domain/schedule/internal.py
src/apps/schedule/service/schedule.py
src/apps/schedule/service/schedule_history.py
src/apps/workspaces/crud/user_applet_access.py
src/infrastructure/database/migrations/versions/2025_02_02_18_39-clean_up_schedule_tables.py

🔗 [Jira Ticket M2-8495](https://mindlogger.atlassian.net/browse/M2-8495)
> [!NOTE]
> This PR is based on #1733. If it is still open, please review that one first
This PR implements the following cleanup operations:
- Adds four new columns to the `events` table:
- `activity_id`: taken from the `activity_events` table
- `activity_flow_id`: taken from the `flow_events` table
- `user_id`: taken from the `user_events` table
- `event_type`: Enum with value `activity` or `flow`
- Removes the `periodicity_id` column from the `events` table
- Migrates all the data from the `activity_events`, `flow_events`, and `user_events` tables into the `events` table
- Drops the `activity_events`, `flow_events`, `user_events`, and `periodicity` tables
- Updates the API code to account for these changes, which …

chore: Schedules database clean up (M2-8495)

---

src/apps/schedule/crud/events.py
src/apps/schedule/service/schedule_history.py

🔗 [Jira Ticket M2-8743](https://mindlogger.atlassian.net/browse/M2-8743)
This PR updates the query being used to find all the events linked to an applet when that applet is updated. This list of events is used as the base for which rows get inserted into `applet_events` whenever the applet version changes without changing any event versions.
Previously, the query being used was excluding individual events by adding the condition `WHERE user_id = NULL`
1. Create an applet with an activity
2. Save the applet
3. Go to the applet owner's PDP schedule tab and create an individual schedule for them
4. Update the applet name
5. Inspect the `applet_events` table to ensure there are entries for each of the events linked to both versions of the applet
This query may help
```sql
SELECT ae.applet_id, …
```

fix: Fix linking of individual events to new applet versions in `applet_events` (M2-8743)

---

src/apps/shared/commands/patches/m2_8568_update_subscale_items_to_greek.py

When web and mobile submits answers, the gender question’s value is not the translated male/female string value, but instead the index of the selected radio button (eg. 0, 1)
When backend retrieves the answer (eg. via `/applet/{applet_id}/activities/{activity_id}/answers/{answer_id}`) it uses the activity history ID provided by the answer to retrieve that version of the activity and it’s items, which it then uses to reconstruct both the question and answer.
Although the `src/apps/shared/commands/patches/m2_8568_update_subscale_items_to_greek.py` script translates the subscale questions and & answers in the `activity_items` table which is used to display the translated text in the web and mobile app, it needed to be update to update the corresponding values in the …

fix: displays translated subscale q/a in dataviz and data export

---

src/apps/activities/api/activities.py
src/apps/activities/services/activity.py
src/apps/activities/tests/test_activities.py
src/apps/activity_flows/service/flow.py
src/apps/applets/api/applets.py
src/apps/applets/service/applet.py
src/apps/schedule/api/schedule.py
src/apps/schedule/db/schemas.py
src/apps/schedule/service/schedule.py
src/apps/schedule/service/schedule_history.py
src/infrastructure/database/migrations/versions/2025_02_27_06_57-add_updated_by_column.py
src/infrastructure/database/migrations/versions/2025_02_27_12_23-add_updated_by_column.py

🔗 [Jira Ticket M2-8760](https://mindlogger.atlassian.net/browse/M2-8760)
This PR adds a new nullable column called `updated_by` to the `event_histories` table that tracks the logged-in user who submits an update to an event that creates a new version, including the first version.
The column is not back-filled for existing records, so they will remain `null`.
I've also done a bit of other cleaning up in this PR based on things I noticed that were out of line:
- Updated the `_unique_user_device_events_history` unique constraint to include the `user_id` column. I forgot to include this in the previous migration
- Updated the `fk_user_device_events_history_user_id_users` foreign key to be `RESTRICT` instead of `CASCADE`. This is in line with the code
- Removed `nullable=True` from the version …

feat: Add `updated_by` column to `event_histories` table (M2-8760)

---

src/infrastructure/database/migrations/versions/2025_02_02_18_39-clean_up_schedule_tables_pt_1.py
src/infrastructure/database/migrations/versions/2025_02_27_16_47-restore_periodicity_table.py

This is a second PR to merge `release/2025.02.3` to `main` after the initial [PR](https://github.com/ChildMindInstitute/mindlogger-backend-refactor/pull/1760) and merge.

Release/2025.02.3 [main] with updated migration

---

src/apps/answers/api.py
src/apps/answers/tests/conftest.py
src/apps/answers/tests/test_answers.py

🔗 [Jira Ticket M2-8482](https://mindlogger.atlassian.net/browse/M2-8482)
This PR updates the validation of the `event_history_id` property in the answer data to work for both activities and flows. Previously it was only working for activities.
The reason it failed is because of an assumption that the `event` data contains both the activity and the flow ID, but this is not the case, it only has one or the other. Thus, we can only perform one comparison based on what type of submission is being done.
1. Create an applet with an activity flow
2. Submit the flow via the mobile app
3. Profit (Confirm that the submission works)
N/A

fix: Update event_history_id validation (M2-8482)

---

README.md
src/apps/shared/commands/patches/m2_8568_update_subscale_items_to_greek.py

- Changed age question to "Ηλικία:" in Greek.
- Updated gender question to "Φύλο:" in Greek.
- Ensured consistent updates for male/female options.
🔗 [Jira Ticket M2-8840](https://mindlogger.atlassian.net/browse/M2-8840)

Update Greek translations for age_screen and gender_screen items (M2-8840)

---

src/apps/activities/domain/scores_reports.py

Adds `PERCENTAGE` to `SubscaleCalculationType` to accept updated 
🔗 [Jira Ticket M2-8433](https://mindlogger.atlassian.net/browse/M2-8433)
Test in conjunction with [Admin PR #2052](https://github.com/ChildMindInstitute/mindlogger-admin/pull/2052)
- Go to Applet Settings > Activity Settings
- Add scored items (Slider, Single Select, Multi Select)
- Enable Score using the item settings menu under "Scores and Alerts"
- Add Subscale configuration selecting "Percentage" in Subscale scoring
- Enable "Calculate total score" and select "Percentage of Item Scores"
- Save applet 
**Expected behavior**: Admin is able to save/submit the applet
Required for https://github.com/ChildMindInstitute/mindlogger-admin/pull/2052

feat: add percentage to SubscaleCalculationType (M2-8433)

---

src/apps/shared/commands/patch_commands.py
src/apps/shared/commands/patches/m2_8175_library_cleanup_for_camhi.py

🔗 [Jira Ticket M2-8175](https://mindlogger.atlassian.net/browse/M2-8175)
This adds a patch script for deleting a specific list of applets from the `library` table for CAMHI, who are going to use the MindLogger Library feature in order to merge activities from several applets into one.
Sharing their applets to the Library is being done strictly to use it as a mechanism for merging activities from multiple applets into one applet (there is no other known convenient way to do this). But once that has been done, those applets need to be **deleted from the library promptly** because we don't actually want these applets to be shared with all MindLogger users.
Since the BE does not have any mechanism for deleting entries from the Library, this script is required. It includes some sanity checks …

chore: Add script to delete specific CAMHI applets from library (M2-8175)

---

src/apps/schedule/crud/schedule_history.py
src/apps/schedule/domain/schedule/public.py

🔗 [Jira Ticket M2-8693](https://mindlogger.atlassian.net/browse/M2-8693)
This PR follows up on #1775 by adding an `activityOrFlowHidden` property to the schedule history response. This came out of a discussion with Natalia and the solution was proposed by Sailaja
1. Create an applet with an activity and a flow and save it
2. Consume the schedule history endpoint with the applet ID
3. Confirm that the `activityOrFlowHidden` property is present for both of them and set to `false`
4. Hide the activity and the flow and save the applet
5. Consume the endpoint again and confirm that additional objects are returned in the response that have the `activityOrFlowHidden` property present and set to `true`
- I'm still deferring the tests for these new endpoints to a separate task

feat: Add activityOrFlowHidden property to schedule history endpoint response (M2-8693)

---

src/apps/answers/api.py
src/apps/answers/tests/test_answers.py

🔗 [Jira Ticket M2-8924](https://mindlogger.atlassian.net/browse/M2-8924)
This PR removes the device ID and event history ID validations in the answer submission endpoint. This should make it possible to submits answers again, even when having invalid values for these parameters.
> [!TIP]
> If you are testing this locally, you answer submission may fail for an unrelated reason. Please comment out [this line](https://github.com/ChildMindInstitute/mindlogger-backend-refactor/blob/f59fc672a77c23596b5e8a3f24199a46beed3a6a/src/apps/answers/crud/answers.py#L506) in your API server to eliminate this possibility
1. Launch the mobile app and start an activity
2. Before submitting, edit or delete the row from both the `user_device_events_history` and `event_histories` tables for the activity you are …

fix: Relax validations during answer submission (M2-8924)

---

src/apps/schedule/service/schedule.py

🔗 [Jira Ticket M2-8924](https://mindlogger.atlassian.net/browse/M2-8924)
This PR adds an if statement that prevents attempted insertion to the `user_device_events_history` table when the user has no events. This can happen for a few reasons, mainly:
- The user has been deleted, but they still have a valid auth token and consume this endpoint via the mobile app
- The user is not part of any applets
1. Create an account in the admin panel, but create no applets
2. Sign in to the mobile app
3. Confirm there is no 500 error on the API server
N/A

fix: Prevent upsert query if events list is empty (M2-8924)

---

src/apps/activities/domain/activity_create.py
src/apps/activities/domain/activity_update.py
src/apps/activities/domain/custom_validation.py
src/apps/activities/domain/response_type_config.py
src/apps/activities/domain/response_values.py
src/apps/activities/tests/fixtures/configs.py
src/apps/activities/tests/fixtures/items.py
src/apps/activities/tests/fixtures/response_values.py
src/apps/applets/tests/test_applet_activity_items.py

Extend the item types with a new option for health record data flow. 
Add models for configuration and value handling.
Update test fixtures and item creation to cover the new functionality.
🔗 [Jira Ticket M2-8826](https://mindlogger.atlassian.net/browse/M2-8826)
🔗 [Jira Ticket M2-8926](https://mindlogger.atlassian.net/browse/M2-8926)
@egodoy-metalab @Phillipe-Bojorquez This PR add a new activity item type, should update tests

Add new item type for health record data (M2-8826) (M2-8926)

---

src/apps/schedule/api/schedule.py
src/apps/schedule/crud/user_device_events_history.py
src/apps/schedule/db/schemas.py
src/apps/schedule/domain/schedule/public.py
src/apps/schedule/service/schedule.py
src/infrastructure/database/migrations/versions/2025_03_20_22_38-add_time_zone_field_to_user_device_.py

🔗 [Jira Ticket M2-8693](https://mindlogger.atlassian.net/browse/M2-8693)
This PR accomplishes the following things:
- Record the user's time zone in the `user_device_events_history` table when they fetch their schedules. This is a new nullable column, and will not be populated for existing records
- Return this time zone, as well as the access before schedule property in the device schedule history endpoint
This PR contains a migrations that needs to be run before any testing can be done
```shell
alembic upgrade head
```
1. Run the mobile app
2. Log in, or swipe refresh
3. Observe the time_zone column in the `user_device_events_history` table
1. Consume the device schedule history endpoint
2. Observe the response for the new properties:
- accessBeforeSchedule
- userTimeZone 
N/A

chore: Some EMA cleanup tasks (M2-8693)

---

copilot/mindlogger-backend/manifest.yml
copilot/scripts/svc-deploy.sh
src/apps/file/test_file.py

🔗 [Jira Ticket M2-8904](https://mindlogger.atlassian.net/browse/M2-8904)
- Fixed unit test suite.  Removed logging output check based on [Tech talk decision](https://mindlogger.atlassian.net/wiki/spaces/MINDLOGGER1/pages/963084689/December+17+2024+-+Tech+Talk#%E2%A4%B4-Decisions)
- Added Datadog environment tags to feature environment resources
- Changed a security group between ALB and Fargate to only allow access to ALB dynamic ports for health checks.  Remediates SSH not blocked finding for GDPR and HIPAA

Adding logic to hardend the ECS security group

---

src/apps/applets/service/applet.py
src/apps/schedule/crud/schedule_history.py
src/apps/schedule/service/schedule_history.py

🔗 [Jira Ticket M2-8973](https://mindlogger.atlassian.net/browse/M2-8973)
🔗 [Jira Ticket M2-8983](https://mindlogger.atlassian.net/browse/M2-8983)
🔗 [Jira Ticket M2-9047](https://mindlogger.atlassian.net/browse/M2-9047)
This PR revises the logic that links versions of schedule events and applets together in the `applet_events` table. The current logic has a bug where an update to an applet that deletes an activity/flow results in the events for that activity/flow being linked to the new version of the applet in `applet_events`.
The root cause is that the linking action was being done before the events for the activity/flow were marked as deleted. This PR moves the linking action to the end of the update method to account for this.
I also took the opportunity to fix the `subject_id` field …

chore: Revise applet-event version linking logic (M2-8973) (M2-8983) (M2-9047)

---

src/infrastructure/database/migrations/versions/2025_04_18_05_24-fix_encrypt_internal_function.py

🔗 [Jira Ticket M2-9066](https://mindlogger.atlassian.net/browse/M2-9066)
This PR updates the `encrypt_internal` postgres function to support non-english characters.
The content of encrypted columns in the database is encrypted/decrypted by SQLAlchemy's `StringEncryptedType` during normal operation of the API. We have created `encrypt_internal` and `decrypt_internal` functions in the database to mirror this, but the definition of the `encrypt_internal` function currently does not support non-english characters because it uses the `length` function to determine the padding to add to the plaintext.
The `length` function counts characters, whereas the `encrypt_iv` function operates on bytes in multiples of the block size. Some non-english characters can represent multiple bytes, and using …

chore: Fix encryption function (M2-9066)

---

src/apps/applets/service/applet.py

🔗 [Jira Ticket M2-9135](https://mindlogger.atlassian.net/browse/M2-9135)
This PR fixes a regression introduced by #1820 wherein old event version weren't being linked to the new applet versions in the `applet_events` table. The bug happens when the applet version is increased by creating a new activity/flow.
1. Create an applet with 1 activity and note the ID of the applet
2. Run the query and observe the results: `SELECT applet_id, event_id from applet_events WHERE applet_id ilike :applet_id || '%'`
3. Confirm that there is one row in the result with the applet_id ending in `_1.1.0`
4. Add a new activity to the applet
5. Run the query again and observe the results
6. Confirm that there are now two (2) additional rows with the applet_id ending in `_2.0.0`. One of these rows should have …

fix: Link old event versions to new applet versions (M2-9135)

---

src/apps/applets/crud/applets.py
src/apps/applets/service/applet.py
src/apps/applets/tests/test_applet.py

🔗 [Jira Ticket M2-8969](https://mindlogger.atlassian.net/browse/M2-8969)
When creating, updating or duplicating applets, applet name uniqueness should now be checked against applets owned by that user (in the same workspace), rather than all applets that the user has access to.
1. Create an applet in a workspace owned by User1 with a name such as "ProblemApplet"
2. Log in as a User2 and create an applet with the same name as above, "ProblemApplet", in the workspace owned by this user
3. Invite User3 to both of these applets as either a manager or editor:
1.  Log in as User1
2.  Invite User3 to "ProblemApplet", and User3 accepts the invitation
3.  Log in as User2
4.  Invite User3 to "ProblemApplet", and User3 accepts the invitation
4. Log in as User3
5. Edit either of the two applets named …

fix: Check applet name uniqueness against owned applets rather than accessible applets (M2-8969)

---

src/apps/answers/crud/answers.py
src/apps/answers/domain/answers.py
src/apps/answers/tests/test_answers.py
src/apps/answers/tests/test_answers_arbitrary.py

🔗 [Jira Ticket M2-9153](https://mindlogger.atlassian.net/browse/M2-9153)
This PR adds a new nullable `scheduledEventHistoryId` property to the data being returned from the `/answers/applet/{applet_id}/data` endpoint. It comes directly from the `event_history_id` column of the answers table.
1. Create a new applet, or use an existing applet
2. Respond to an activity in the applet
3. Export the applet data
4. Inspect the response from the `/answers/applet/{applet_id}/data` endpoint in dev tools
5. Confirm that the `scheduledEventHistoryId` property is present
N/A

feat: Return `scheduledEventHistoryId` from `/answers/applet/{applet_id}/data` endpoint (M2-9153)

---

src/infrastructure/dependency/structured_logs.py

Fixed logging where traces and logs are not associated

fix: Associating Datadog logs and traces

---

src/apps/applets/commands/applet/seed/command.py
src/apps/applets/service/applet.py
src/apps/applets/tests/test_applet.py
src/apps/integrations/oneup_health/tests/test_oneup_health.py

🔗 [Jira Ticket M2-8969](https://mindlogger.atlassian.net/browse/M2-8969)
This change allows a user A who owns an applet having the same name as user B's applet, and is also a manager/editor of user B's applet, to successfully update user B's applet.
From the Admin App:
1. As User A, create an applet `test applet same name`.
2. As User B, create an applet with the same name, `test applet same name`.
3. Add User A as a manager to User B's applet.
4. Log in as User B, navigate to User B's workspace.
5. Edit User B's applet, change the applet's description, and Save & Publish.
**Expected outcome:** Saving the applet should succeed.

fix: Support nuanced applet update scenario (M2-8969)

---

src/apps/schedule/crud/schedule_history.py
src/apps/schedule/crud/user_device_events_history.py
src/apps/workspaces/crud/user_applet_access.py
src/apps/workspaces/domain/workspace.py
src/apps/workspaces/filters.py

🔗 [Jira Ticket M2-9108](https://mindlogger.atlassian.net/browse/M2-9108)
🔗 [Jira Ticket M2-9161](https://mindlogger.atlassian.net/browse/M2-9161)
This PR updates a couple API endpoints in preparation for a corresponding PR that resolves the captioned tickets.
This ticket is about retaining schedule history in the export file for participants whose subjects are soft deleted. The FE uses the workspace respondents endpoint to fetch the complete list of participants in the applet, and generate an enumerated export file for each of them for the selected date range. This PR updates the workspace respondents endpoint to optionally include soft deleted participants, and adds two key properties to the response:
- `subjectIsDeleted` - Whether the subject is soft deleted within a given applet
- …

fix: EMA Fast Follows 2 (M2-9108) (M2-9161)

---

src/apps/integrations/oneup_health/service/task.py
src/apps/integrations/oneup_health/tests/test_task.py
src/config/oneup_health.py

(https://mindlogger.atlassian.net/jira/servicedesk/projects/MLA/knowledge/articles/340623543?spaceKey=MLA)
🔗 [Jira Ticket M2-8982](https://mindlogger.atlassian.net/browse/M2-8982)
- Adds a max retries parameter to OneUpHealth config.
- Checks and retries up until max retries are spent
- Logs adequately

feat: Add max retries and logging to OneUpHealth tasks (m2-8982)

---

src/apps/invitations/test_invite.py

Adding 3 scenarios, invitation scenarios:
Respondent, editor, and coordinator can not invite a new reviewer
On this PR, we are adding 3 new scenarios from the old TAF API to the Backend repo, Those test are:
403 Forbidden (Coordinator can NOT invite new reviewer for a specific respondent)
403 Forbidden (Editor can NOT invite new reviewer for a specific respondent)
403 Forbidden (Respondent can NOT invite new reviewer for a specific respondent)
Code in TAF
https://github.com/ChildMindInstitute/MindLogger-TAF/blob/f9dcfb7aa516ecee3c8530c7e8675f7bf1135854/tests/api/permissions/administration.tests.ts#L854
🔗 [Jira Ticket M2-9264](https://mindlogger.atlassian.net/browse/M2-9264))
- The new 3 test, migrated from TAF
Check if the logic is correct
Run the test and check if …

Adding new scenarios in invite test

---

src/apps/answers/api.py
src/apps/answers/tests/test_answers.py
src/apps/integrations/oneup_health/service/ehr_storage.py

Addresses an issue where the EHR zip download was not correctly utilizing the storage path. This change ensures the correct path is used when downloading the zip file.
- Modifies the `download_ehr_zip` function to accept a `storage_path` parameter.
- Updates the function call in `applet_ehr_answers_export` and test cases to include the `ehr_storage_uri`.
- Uses storage path to generate key for download
🔗 [Jira Ticket M2-9443](https://mindlogger.atlassian.net/browse/M2-9443)

fix: Refactors ehr zip download to use storage path (M2-9443)

---

src/apps/schedule/service/schedule.py

Improves schedule performance by optimizing event retrieval:
- Reduces database queries by fetching events in bulk for multiple applets.
- Consolidates event data retrieval into fewer operations using maps.

Optimizes schedule event retrieval for performance

---

src/apps/authentication/errors.py
src/apps/transfer_ownership/tests.py

🔗 [Jira Ticket M2-9399](https://mindlogger.atlassian.net/browse/M2-9399)
- Adding a new expected message error for the Transfer Ownership
- Adding new migrated test cases from TAF
> test_manager_can_not_transfer_ownership
> test_respondent_can_not_transfer_ownershipto
> test_reviewer_can_not_transfer_ownership
> test_editor_can_not_transfer_ownership
> test_coordinator_can_not_transfer_ownership
Run the tests mentioned above

M2 9399 transfer ownership

---

src/infrastructure/database/migrations/versions/2025_05_21_10_55-clean_up_applet_events_table.py

🔗 [Jira Ticket M2-9237](https://mindlogger.atlassian.net/browse/M2-9237)
> [!NOTE]
> This PR should **not** be reviewed until this ticket has been prioritised
This PR adds a migration that moves the erroneous entries in the `applet_events` table to a temporary table called `applet_events_cleanup` for eventual permanent deletion. This should fix failed data exports in applets with deleted activities/flows before the implementation of M2 9161.
Prior to the implementation of that ticket, rows were created in the applet_events table linking activities/flows (and their events) with versions of the applet they don't exist in. The downstream effect of this is that the API endpoint that returns applet schedule history fails because the query returns `NULL` values for the result of the JOINs with …

fix: Add cleanup migration for erroneous records in applet_events (M2-9237)

---

src/apps/logs/domain/notification.py

🔗 [Jira Ticket M2-8994](https://mindlogger.atlassian.net/browse/M2-8994)
- Added Pydantic pre-validator to `NotificationLogCreate` schema
- Converts JSON string fields to arrays for backward compatibility
- Handles edge cases (null values, malformed JSON) gracefully
Test the backward compatibility with these curl commands:
1. **Old mobile format (JSON strings)**:
```bash
curl -X POST "http://localhost:8000/logs/notification" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer YOUR_TOKEN" \
-d '{
"action_type": "trigger-notification",
"user_id": "test@example.com",
"device_id": "old-mobile-001",
"notification_descriptions": "[{\"id\": \"1\", \"title\": \"Test\"}]",
"notification_in_queue": "[]",
"scheduled_notifications": null
}'
Expected outcome: HTTP 200 - …
```

  fix: add backward compatibility for notification logs API (M2-8994)
